### ISSUE TITLE
watch mode should not get triggered by package downloads

### ISSUE THREAD

**Issue by avh4** [rtfeldman/node-test-runner#100]
To recreate, use a project that has many dependencies listed in `tests/elm-package.json`:

```sh
rm -Rf tests/elm-stuff
elm-test --watch
```

On the first run, elm-test will download the dependencies, but when the dependencies are downloaded, watch mode will see a bunch of new elm files appear under elm-stuff, and will kick off a bunch of simultaneous new builds while the first build is still downloading dependencies (and all the new builds will start downloading dependencies too!)

I think there are two things that ideally should both be done:
  - Don't start a new build while a previous one is still running
  - Don't watch files under elm-stuff (though maybe some people would actually want this?)

**Comment by rtfeldman** [comment]
> Don't watch files under elm-stuff

This part is implemented on a branch and will be in the next release.

I agree that the other one is a good idea, but it's harder. Might be worth a separate issue?
