### ISSUE TITLE
Release new NPM version from master

### ISSUE THREAD

**Issue by lpil** [rtfeldman/node-test-runner#108]
Hello!

It'd be great if the NPM package had the latest updates, such as the fix for watching the `src` directory :)

Cheers,
Louis

**Comment by rtfeldman** [comment]
@lpil there's a beta out, which you can get with `npm install -g elm-test@beta` - can you let me know if this solves it for you? (Note: there were breaking changes!)

**Comment by lpil** [comment]
Alas, I don't currently have any Elm projects!

**Comment by rtfeldman** [comment]
Fair enough! I'm gonna close this then...beta should turn into full release soon! 😸

**Comment by lpil** [comment]
Thanks. I look forward to checking it out next time I have some frontend to do :)
