### ISSUE TITLE
New release coming?

### ISSUE THREAD

**Issue by squaresurf** [rtfeldman/node-test-runner#113]
I'm curious if there is a new release coming anytime soon. I see that the latest release was made in November, but I see newer versions of files. Specifically https://github.com/rtfeldman/node-test-runner/blob/master/bin/elm-test#L280 appears as though it would fix the `--watch` command so that it would watch the application source as well as the tests.

**Comment by rtfeldman** [comment]
Yep! Currently in alpha.

You can [try it out right now](https://groups.google.com/d/msg/elm-dev/7mmElgi4QM8/XCpNnRrVAQAJ) if you'd like!

**Comment by squaresurf** [comment]
Thank you @rtfeldman. I ended up switching to [lobo](https://github.com/benansell/lobo) as it not only watches both tests and application source files, but it also helps me keep my test elm-package.json in sync.

Thank you for your work on this. I really appreciate it.

**Comment by squaresurf** [comment]
Great! I'll have to give that a look.
