### ISSUE TITLE
Test files with mismatched module names are sometimes silently ignored

### ISSUE THREAD

**Issue by tgecho** [rtfeldman/node-test-runner#118]
If I save the following test as `FooTests.elm` (mismatched module name)

```
module BarTests exposing (..)

import Test exposing (..)
import Expect

all : Test
all =
    test "one" <| \() -> Expect.equal 1 1
```

...and run `elm-test` it will silently skip this entire file. If I pass the file path (`elm-test FooTests.elm`) I get the appropriate `The module name is messed up...` error.

**Comment by tgecho** [comment]
And... now I can't reproduce it. The warning shows up every time. Feeling crazy. Closing for now. Sorry!

**Comment by tgecho** [comment]
Ok, I hit this again and think I've nailed down reproduction steps.

Start with an existing test file. For example, this `Foo.elm`

```
module Foo exposing (..)

import Test exposing (..)
import Expect


one : Test
one =
    test "one" <| \() -> Expect.equal 1 1
```

Running elm-test will get the usual `... Running 1 test. ...` etc output.

Duplicate the test file (say, to `Bar.elm`, but forget to change the module declaration at the top (so it still says `module Foo exposing (..)`.

The only indication that `elm-test` is skipping your file will be the fact that it reports `Running 1 test`.

**Comment by tgecho** [comment]
The other fun variation is if you rename the top level variable in `Bar.elm` I got something like this:

```
Cannot find variable `Foo.two`.

17|     [     Test.describe "Foo" [Foo.two] ]
                                                    ^^^^^^^
`Foo` does not expose `two`.
```

So it seems that `Bar.elm` is actually shadowing `Foo.elm`.

**Comment by rtfeldman** [comment]
This should give a more descriptive error now.

If the shadowing one is still reproducible, can you open a separate issue for it?

**Comment by tgecho** [comment]
Not quite gone, I'm afraid.

PR to hopefully finish this one off: https://github.com/rtfeldman/node-test-runner/pull/121

The shadowing appears to be eliminated as a byproduct of the rest of this fix.
