### ISSUE TITLE
Doesn't work on Travis CI

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/node-test-runner#125]
[Failing on Linux on Travis](https://travis-ci.org/rtfeldman/node-test-runner/jobs/230229653#L482)
[Failing on macOS on Travis](https://travis-ci.org/rtfeldman/node-test-runner/jobs/230229655#L1728)

On both Linux and macOS on Travis, it fails with:

```
### Testing elm-test on example/
Running: elm-test tests/*Pass*
/Users/travis/build/rtfeldman/node-test-runner/example/tests/elm-stuff/build-artifacts/0.18.0/elm-community/elm-test/4.0.0: /Users/travis/build/rtfeldman/node-test-runner/example/tests/elm-stuff/build-artifacts/0.18.0/elm-community/elm-test/4.0.0: getSymbolicLinkStatus: does not exist (No such file or directory)
```

https://github.com/stoeffel/elm-interface-to-json/issues/2

**Comment by jwoudenberg** [comment]
One more data point: I just ran the tests on my linux machine and they passed :/.

**Comment by jwoudenberg** [comment]
Nope, running `elm-test` on the `upgrade-elm-test` branch is green for me (using elm-test from master). I can an error on the `mocha *.js` part, but that's something different than what I'm seeing on Travis.

**Comment by eeue56** [comment]
@jwoudenberg The bundled binary was an OS X binary. @rtfeldman has since fixed that, so it installls and runs on Linux now.

**Comment by jwoudenberg** [comment]
Ah, so that was an altogether different problem. Thanks! So only irreproducible travis errors left :(

**Comment by rtfeldman** [comment]
Fixed! Thanks @jwoudenberg!
