### ISSUE TITLE
elm-test init fails

### ISSUE THREAD

**Issue by mbuscemi** [rtfeldman/node-test-runner#126]
Running `elm-test init` yields `Error reading elm-package.json: Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/elm-test/templates/tests/elm-package.json'`.

Installed using `npm install -g elm-test@beta`.

**Comment by rtfeldman** [comment]
@mbuscemi just published a new `beta` - can you see if this is still reproducible for you?

**Comment by rtfeldman** [comment]
I haven't been able to reproduce this on the current `beta` (`beta14`) - @mbuscemi if you can still reproduce on the latest build, please let me know so we can reopen!
