### ISSUE TITLE
`elm-test init` should create example test in ./tests/ instead of in ./

### ISSUE THREAD

**Issue by avh4** [rtfeldman/node-test-runner#13]

**Comment by rtfeldman** [comment]
I dunno about this. Some people use `tests/`, some use `test/`, some use `spec/`, some use `../test/` etc - I don't know if we can do a good job guessing this.

Personally I think we should just leave this as-is. Thoughts @avh4 ?

**Comment by avh4** [comment]
I think we should pick one and make it the default.  In any case, putting it in `./` is bad because normally you are going to need a separate `elm-package.json` for your tests vs your main code.

**Comment by rtfeldman** [comment]
:+1: I buy that.

**Comment by kommen** [comment]
Coming from the ruby world, I use `test/`.

I think it would be nice if `elm-test init` would suggest to create a separate `elm-package.json` as well?

**Comment by mgold** [comment]
This seems is now the current behavior.
