### ISSUE TITLE
Test's running directory

### ISSUE THREAD

**Issue by alvivi** [rtfeldman/node-test-runner#132]
After updating to `0.18.3` tests run into the npm installation path. For our tests, this means that they stop working because they cannot access to their local fixtures. We can solve this using an `elm-test` local installation.

If there is no plan to return to previous behavior, I think that this should be documented somewhere at least.

**Comment by rtfeldman** [comment]
Sorry, I don't understand. 😅

Could you show me a [SSCCE](http://sscce.org/) demonstrating the problem?

**Comment by rtfeldman** [comment]
Closing this pending clarification on what exactly the problem is. 🙂
