### ISSUE TITLE
Runner overly sensitive to module declaration

### ISSUE THREAD

**Issue by Janiczek** [rtfeldman/node-test-runner#136]
This module declaration:
```elm
module MyTests
    exposing
        ( test1
        , test2
        , test3
        )
```
triggers this error:
`/path/to/MyTests.elm is missing a module declaration.`
while this "all-on-one-line" style works:
```elm
module MyTests exposing (test1, test2, test3)
```

Relevant discussion:
https://elmlang.slackarchive.io/testing/page-34/ts-1495465366320139

**Comment by zwilias** [comment]
Thinking about this some more, I'm not sure the current approach can be extended to work for all valid inputs:

- there are a lot of places in a module declaration where whitespace is allowed
- comments in Elm count as whitespace
- comments can be nested

I wonder if building a little tokenizer would be a better way to handle this.

**Comment by rtfeldman** [comment]
Thanks @eeue56!

**Comment by Janiczek** [comment]
@rtfeldman :+1: This solves the bug for me. And the other bug from yesterday resurfaced! Will create an issue :)
