### ISSUE TITLE
Feature Request: Add OS Notifications

### ISSUE THREAD

**Issue by eliaslfox** [rtfeldman/node-test-runner#146]
Jest allows firing notifications after every test run. This allows for refactoring tests without having to switch windows, only to see that all of your tests have passed.

Test Pass Notification:
![screen shot 2017-05-28 at 11 22 48 pm](https://cloud.githubusercontent.com/assets/6886632/26538629/e04f8c9c-43fc-11e7-9299-1e5af8ad82a2.png)

Test Fail Notification:
![screen shot 2017-05-28 at 11 23 20 pm](https://cloud.githubusercontent.com/assets/6886632/26538646/fbd97a86-43fc-11e7-9546-c6b90b2025e3.png)

**Comment by rtfeldman** [comment]
I've never personally used a test runner with notifications, so I'm curious about a few things here.

1. What does the workflow look like where these would be most desirable? Running in `--watch` mode, editing the tests, and then wanting to see that things pass or fail without having to switch back to the console? Or is it more when you're editing your application's source code (not the tests) and want to know that something you just changed broke (or fixed) a test?
2. Should these be enabled by default in `--watch` mode?
3. Under what circumstances would these be annoying?
4. Is it possible to have an implementation in which they are never annoying?

**Comment by eliaslfox** [comment]
1. In watch mode, a notification is triggered after each file save. I usually always have my tests running in watch mode, rather I'm editing the source code or tests. That way I get a notification if I break code or tests.

2. I can't think of a reason not to, other than that it would be unexpected.

3. They shouldn't be very annoying because it's uncommon to save files more that once every 30-90 seconds. However I use osx, and the experience might be different on other platforms. One other possibly annoying factor is that it would fill up your notification center pretty quickly.

4. If they didn't take up space in the notification log, and never make sound.

**Comment by Janiczek** [comment]
3. IntelliJ IDEA saves on blur, so I wonder what workflow would work there. The users would probably retrain to press Ctrl+S to save-therefore-run-the-tests, or switch windows anyway to trigger that, but then if they'd change to the tests window, they wouldn't need the notification, seeing the results in the console...

**Comment by eliaslfox** [comment]
Yeah you would have to hit save manually. Maybe we could fire notifications only if the window wasn't visible. That way if you switched to see your tests you wouldn't see an unneeded notification.

**Comment by rtfeldman** [comment]
> Maybe we could fire notifications only if the window wasn't visible.

🤔 is it possible to tell that from a terminal?

**Comment by rtfeldman** [comment]
> This allows for refactoring tests without having to switch windows, only to see that all of your tests have passed.

I've thought about this a bunch more, and my conclusion is that this feature should be part of editor plugins, not the CLI itself.

The goal is to see the results of the tests without switching windows, and editors can do the best job presenting that to the user in a nice way. They know when the window is focused, they can run the tests themselves (and consume the output via the JSON reporter), and they can report the outcome to the user in a nicer way than an OS notification by reporting it directly in the editor itself.
