### ISSUE TITLE
elm-test binary not found

### ISSUE THREAD

**Issue by renatomassaro** [rtfeldman/node-test-runner#150]
As requested, I'm reopening the issue here.

I've been running elm-test on my build servers for over a month, but this week (not sure when) a weird error started showing up. I'm not sure whether it's directly related to elm-test itself, but I'd be very grateful if you could give me a hint where to look.

After running `elm-test`, I get 

```
Success! Compiled 1 module.
Successfully generated /dev/null
Unfortunately, there are no elm-test 0.18.4 binaries available on your operating system and architecture.
<instructions on how to build from source>
```

I use FreeBSD and it's right, I can't install it via `npm`. I've built elm directly from source, and elm is working fine. 
I don't install `elm-test` globally. Instead, it is installed on every build along the npm dependencies, and I call it directly from `node_modules/.bin/elm-test`. Passing the `--version` arg returns 0.18.4.

I thought maybe someone was looking for `elm-test` on $PATH. So I `npm install -g elm-test`, having the binary available globally at `/usr/local/bin/elm-test`, and the same error persists. Passing `--version` to this binary returns 0.18.4.

So... do you have any idea what may be the cause? I don't think the OS is the problem, I've been using both elm and elm-test on it for some time. Elm is compiling the project just fine. In fact, when calling `elm-test`, it downloads the dependencies (if needed), compiles the app, generates /dev/null (!) and then claims there are no binaries available.

In case it's of any use, I have a [console output](https://ci.hackerexperience.com/job/HackerExperience/job/HEBorn/job/PR-106/20/console) that lists all commands and their output. Search for /dev/null to quickly find the relevant part.

There is no error when using version 0.18.2 of `elm-test` from npm. It won't work on 0.18.3 onwards. I'm using elm-test 3.1.0; I can't test/upgrade to 4.1.0 because of a weird package compatibility issue (https://github.com/elm-lang/elm-package/issues/274).

I'm using FreeBSD 11.0 on a amd64 architecture.

**Comment by rtfeldman** [comment]
Hm...@renatomassaro can you run `node -p "[process.arch, process.platform].join(' ')"` and paste the output here?

**Comment by rtfeldman** [comment]
Gonna close this due to inactivity...happy to reopen if I can get the info in the [above post](https://github.com/rtfeldman/node-test-runner/issues/150#issuecomment-306067424)!
