### ISSUE TITLE
Add sync argument to enable syncing existing tests elm-package.json

### ISSUE THREAD

**Issue by hakonrossebo** [rtfeldman/node-test-runner#157]
As already solved on init, can we also have this possibility for existing tests? This would read elm-package.json from root and sync with elm-package.json in tests.

**Comment by zwilias** [comment]
Hey @hakonrossebo.

You can already do this using `elm-test --add-dependencies tests/elm-package.json` which will copy over any missing dependencies from the `elm-package.json` in the current directory, to the specified target.

Does that cover your use case?

**Comment by hakonrossebo** [comment]
Thanks. Exactly what I wanted. Closing this issue.
