### ISSUE TITLE
Large Slowdown in Travis Builds Between v0.18.2 & 0.18.4

### ISSUE THREAD

**Issue by prikhi** [rtfeldman/node-test-runner#159]
Somewhere between v0.18.2 & 0.18.4 the time to run `elm-test` on Travis slowed down a lot.

Discovered this on the `elm-community/list-extra` repository. 

This build with 0.18.2 took 175 seconds for 95 tests:
https://travis-ci.org/elm-community/list-extra/builds/240595262#L392

And this build w/ 0.18.4 took 420 seconds for 89 tests:
https://travis-ci.org/elm-community/list-extra/builds/239274263#L463

I had a build w/ 0.18.4 that took 750 seconds for 95 tests, but someone restarted the build after I deleted the branch so the log is just errors now :(

**Comment by prikhi** [comment]
Switching the OS to OSX reduces the run time to 9 seconds:
https://travis-ci.org/elm-community/list-extra/builds/241797765#L465

**Comment by rtfeldman** [comment]
Hm...I wonder if the discrepancy between Linux and macOS has to do with `elm-interface-to-json` parallelization - can you try doing [the `sysconfcpus` trick](https://github.com/rtfeldman/elm-css/blob/master/.travis.yml) and see if that improves things?

**Comment by prikhi** [comment]
Yeah that's what I ended up doing & it brought the elm-test time down from 10+ minutes to ~15 seconds:
https://travis-ci.org/elm-community/list-extra/builds/241758038#L863

One other thing I noticed was that previous `list-extra` builds would run for 12+ minutes without getting the "No output for 10 minutes" error, so those were at least producing some output in the first 10 minutes, ?but the latest version seems to only produce output once all the runs are complete?

**Comment by rtfeldman** [comment]
>  the latest version seems to only produce output once all the runs are complete

I don't think there have been any changes to output behavior, so I'm not sure why this might be... 🤔

**Comment by zwilias** [comment]
Perhaps it's because we do two compiles, making the hit of not using the sysconfcpu trick that much leather?

**Comment by prikhi** [comment]
> I don't think there have been any changes to output behavior, so I'm not sure why this might be... :thinking:

Not sure if that's actually true, just what it seemed like as I was watching the build log on travis

**Comment by rtfeldman** [comment]
My conclusion here is that `sysconfcpus` is now important for `elm-test` as well as for `elm-make`. Hopefully someday in the future, this Haskell/Linux concurrency bug will get fixed and we can use binaries normally. 😛
