### ISSUE TITLE
UI indicating progress of compilation

### ISSUE THREAD

**Issue by avh4** [rtfeldman/node-test-runner#170]
Related to https://github.com/rtfeldman/node-test-runner/issues/169

This issues is for showing progress of the compilation step (before and after running interface-to-json).

`elm-make` normally shows a progress bar, and `elm-test` shows the final output of `elm-make`, so I'm guessing that `elm-make`'s progress is not being shows because of the buffering of the pipes when elm-test spawns the elm-make process: presumably elm-makes doesn't print a newline until the compilation completes, and if we spawn it with line buffering, then the progress indicator won't be shown.  If that's actually what's happening, then the fix for this would be to change the way elm-test spawns elm-make, either changing it to inherit stdout, or changing the stdout pipe to buffer in a different way.

**Comment by rtfeldman** [comment]
@avh4 I think this is fixed in the current release - can you confirm it's working for you locally?

**Comment by avh4** [comment]
Yes, resolved in 0.18.8-beta8
