### ISSUE TITLE
CPU pegged in --watch mode

### ISSUE THREAD

**Issue by nateabele** [rtfeldman/node-test-runner#195]
On OSX (10.12.6) when running `elm-test` with `--watch`, CPU utilization would hover between 110 and 150% — even when completely idle.

Going into my global `elm-test` Node module folder and manually installing `fsevents` resolved the issue. (FWIW, I had the same issue using `elm-live`, with the same resolution).

Still trying to see about a test case... my hunch so far based on research and observation is that it's triggered by watching large, deeply-nested directories (my Elm stuff is embedded in a fairly large project).

**Comment by rtfeldman** [comment]
@nateabele https://github.com/rtfeldman/node-test-runner/pull/197 should have fixed this - can you try `npm install -g elm-test@beta` and see if this is fixed for you?

**Comment by nateabele** [comment]
Testing... one thing I just noticed in the process is that the beta bails out on compiler errors, even in `--watch` mode. Lemme know if you're tracking issues on that version and I can open another one.

**Comment by nateabele** [comment]
Had to change the tests around a bit to get it to execute, but I'm currently stuck on this:

```
I found multiple modules named 'Test.Runner.Node'.

Module 'Test.Generated.Main1561647650' is trying to import it.

Modules with that name were found in the following locations:

    directory /Users/nate/.node/lib/node_modules/elm-test/src/Test/Runner/Node.elm
    package rtfeldman/node-test-runner
```

Tried nuking and re-installing, to no avail. Suggestions?

**Comment by zwilias** [comment]
You might have a leftover dependency on `rtfeldman/node-test-runner` in your `elm-package.json` - try removing that :)

**Comment by nateabele** [comment]
@zwilias That was it. 😄 Thanks.

**Comment by rtfeldman** [comment]
> one thing I just noticed in the process is that the beta bails out on compiler errors, even in --watch mode.

I tried to reproduce this locally and wasn't able to, so a separate issue with steps to reproduce would be great!

**Comment by andys8** [comment]
@rtfeldman #197 only fixed the problem that the test runner can be triggered multiple times in 500 ms.

**Comment by rtfeldman** [comment]
@nateabele I tried publishing a version that includes `fsevents` prepackaged...mind removing `fsevents` from your global install, and seeing if `npm install -g elm-test@beta` now works? (I just published it, so probably have to uninstall the old `elm-test` first.)

**Comment by nateabele** [comment]
Yup, this does the trick! Thanks, @rtfeldman. Just FYI, I had to install it from the GitHub URL, because `elm-test@beta` looks for `elm-test@0.18.9-beta2`, which doesn't seem to exist, and errors out with what looks like a slightly misleading error:

```
Unfortunately, there are no elm-test 0.18.9 binaries available on your operating system and architecture.

If you would like to build Elm from source, there are instructions at https://github.com/elm-lang/elm-platform#build-from-source
```

Guessing it's just a version mismatch somewhere.
