### ISSUE TITLE
Piping JUnit output to a file leads to invalid XML

### ISSUE THREAD

**Issue by NeverwinterMoon** [rtfeldman/node-test-runner#205]
According to this [JUnit XML reporting file format](http://llg.cubic.org/docs/junit/), `<testsuites>` element is optional if there is only one `<testsuite>` element (which is exactly what is produced by the elm-test JUnit reporter). Still, Bamboo's JUnit Report parser plugin fails with "Failed to parse test result file" with the current elm-test output...

I've tried out adding the `<testsuites>` wrapper without any other attributes and that satisfied Bamboo.

Here is what I tried: https://github.com/NeverwinterMoon/node-test-runner/commit/c6a4375b5e84a8b4f40df8229e14bfaf32d88ef4#diff-d9ad54ded24bfa8a4e606a416e682c78R123

This is done on top of `0.18.7` as this is the version we were using. 

If this fix is OK, I could do a pull request on top of the `0.18.8`.

**UPDATE 2017-08-30 12:06**

Yeah, it seems like it might be some issue specific to only one of the Bamboo agents we have. I've contacted Atlassian and they claimed that having `<testsuite>` is enough. I then tried running the same plan on a different Bamboo agent without having `<testsuites>` and it worked indeed. Going to investigate a little bit more.

**UPDATE 2017-08-30 12:18**

OK, I was retarded all along. The problem is this: node-test-runner reporter outputs the report to stdout but I pipe the output to an XML file for Bamboo to read it, like so: `"test:elm": "elm-test --report=junit > junit_elm.xml"`. This actually works fine if node-test-runner doesn't produce any other output to stdout, which it does quite often, like this: `Downloading binaries from https://dl.bintray.com/elmlang/elm-test/0.18.7/linux-x64.tar.gz`. So, obviously, if this ends up in the XML file, JUnit parse will fail.

Is there away to configure node-test-runner to write the report itself not to stdout but to file immediately? Or maybe there is a nice way to configure this without changing the project?

I could try to output only the last line of stdout output to file, but without using any additional tools, I know how to make it work on a unix environemnt (using `tail`), but we need this to work on all platforms.

I'll change the title of the issue to reflect the problem.

**Comment by rtfeldman** [comment]
> This actually works fine if node-test-runner doesn't produce any other output to stdout, which it does quite often, like this: `Downloading binaries from https://dl.bintray.com/elmlang/elm-test/0.18.7/linux-x64.tar.gz`

This is the bug right here. What you tried is supposed to Just Work; the CLI is supposed to be totally silent other than printing the JUnit XML at the very end.

Sorry about that! I'll try to figure out when it's misbehaving and silence those cases.

**Comment by rtfeldman** [comment]
@NeverwinterMoon I'm having trouble reproducing this locally. If I delete my `elm-stuff` and run `elm-test --reporter=junit > out.xml` in the `examples/` directory of this project, it works as expected.

Can you give me some steps to reproduce?

**Comment by NeverwinterMoon** [comment]
@rtfeldman This can be reproduced by doing a fresh install of `elm-test` module.  Oh, and we don't use the global install of `elm-test`, instead, we install it as a dev dependency. Then we have a script in `package.json`, like this: `"test:elm:report": "elm-test --report=junit > junit_elm.xml"`. Bamboo runs that script using `npm run test:elm:report`

To reproduce with the local install, basically:

1. remove `elm-test` folder from `node_modules`
2. run `npm install` -> `elm-test` will be installed, but without the binaries inside `node_modules\elm-test\bin`
3. run `elm-test --reporter=junit > out.xml`. This will download the aforementioned file and create 2 files inside `node_module\elm-test\bin`: `._elm-interface-to-json.exe` and `elm-interface-to-json.exe` (I tested this on Windows machine now, but the same problem arises on the Linux ones).

Optionally, just delete the 2 files from the bin mentioned in point 3 above and run  `elm-test --reporter=junit > out.xml`.

So, every `elm-test` run after a fresh `npm install` will run into this problem. In our Bamboo set-up we have a lot of agents - so if the build happens to be on an agent that never had it before, the JUnit report will contain the download info. Also, if we force a clean checkout for the Bamboo job, the same would happen.

Just now tested with the global `elm-test` install and even though the same two files are downloaded only when I first run `elm-test`, the output is not printed and does not end up in the `out.xml`. But we do prefer to have only localized dependencies in our Bamboo runs.

**Comment by rtfeldman** [comment]
> Just now tested with the global elm-test install and even though the same two files are downloaded only when I first run elm-test, **the output is not printed and does not end up in the `out.xml`**

(Emphasis mine.)

@NeverwinterMoon It's very strange that the locally-installed version would have this problem but the globally-installed version would not. I can't think of any reason they'd differ unless one was a different version than the other.

Can you run `elm-test --version` on the local one as well as the global one and tell me what they say?

**Comment by NeverwinterMoon** [comment]
@rtfeldman Yep, you are correct, of course. We do use `0.18.7` in our project but when I just ran `npm install -g elm-test` just a few minutes ago, it did install `0.18.8`. Tried again, this time with `0.18.7` installed globally and the same problem did appear. It seems the smart move would be to upgrade project dependency from `0.18.7` to `0.18.8`...

**Comment by rtfeldman** [comment]
Ah nice! Please let me know if that fixes it. 😄

**Comment by NeverwinterMoon** [comment]
@rtfeldman OK, `0.18.8` most certainly doesn't produce the download message in the output, but it actually produces a broken JUnit report (at least for Bamboo, that is).

Here is the report done by `0.18.7`:
```
<?xml version="1.0"?><testsuite name="elm-test" package="elm-test" tests="26" failed="0" errors="0" time="0.018"><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 01-01-2000] and [age category = Adult] [with] errors" time="0"/><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 01-01-1999] and [age category = Adult] [without] errors" time="0"/><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 31-12-2010] and [age category = Child] [with] errors" time="0.001"/><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 02-01-2011] and [age category = Child] [with] errors" time="0"/><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 01-01-2011] and [age category = Junior] [without] errors" time="0"/><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 01-01-2011] and [age category = Child] [with] errors" time="0"/><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 31-12-2011] and [age category = Child] [without] errors" time="0"/><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 02-01-2012] and [age category = Child] [without] errors" time="0.001"/><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 31-12-2012] and [age category = Child] [without] errors" time="0.002"/><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 01-01-2016] and [age category = Child] [without] errors" time="0"/><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 01-01-1982] and [age category = Adult] [without] errors" time="0.001"/><testcase classname="ButtonWithSpinnerTest view with spinner and processing state" name="has processing class" time="0.001"/><testcase classname="ButtonWithSpinnerTest view with spinner and processing state spinner container" name="has inner HTML with spinner itself (as SVG)" time="0"/><testcase classname="ButtonWithSpinnerTest view with spinner and processing state" name="is a button with proper classes and attributes" time="0.001"/><testcase classname="ButtonWithSpinnerTest view with spinner and processing and disabled state" name="has processing class" time="0"/><testcase classname="ButtonWithSpinnerTest view with spinner and processing and disabled state spinner container" name="has inner HTML with spinner itself (as SVG)" time="0.001"/><testcase classname="ButtonWithSpinnerTest view with spinner and processing and disabled state" name="is a button with proper classes and attributes" time="0"/><testcase classname="ButtonWithSpinnerTest view with spinner root element when initialState" name="does not have processing class" time="0"/><testcase classname="ButtonWithSpinnerTest view with spinner root element when initialState" name="does not have the spinner container" time="0"/><testcase classname="ButtonWithSpinnerTest view with spinner root element when initialState" name="is a button with proper classes and attributes" time="0.001"/><testcase classname="ButtonWithSpinnerTest view with spinner and disabled state" name="does not have processing class" time="0.004"/><testcase classname="ButtonWithSpinnerTest view with spinner and disabled state" name="does not have the spinner container" time="0.001"/><testcase classname="ButtonWithSpinnerTest view with spinner and disabled state" name="is a button with proper classes and attributes" time="0.001"/><testcase classname="ButtonWithSpinnerTest view initModel root element" name="does not have processing class" time="0"/><testcase classname="ButtonWithSpinnerTest view initModel root element" name="does not have the spinner container" time="0"/><testcase classname="ButtonWithSpinnerTest view initModel root element" name="is a button with proper class" time="0.003"/></testsuite>
```

And here is the output for exactly the same tests done by `0.18.8`:
```
<?xml version="1.0"?><testsuite name="elm-test" package="elm-test" tests="26" failed="0" errors="0" time="192"><testcase>7</testcase><testcase classname="ButtonWithSpinnerTest view with spinner root element when initialState" name="does not have the spinner container" time="0.003"/><testcase>15</testcase><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 01-01-1982] and [age category = Adult] [without] errors" time="0.002"/><testcase>23</testcase><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 31-12-2010] and [age category = Child] [with] errors" time="0.001"/><testcase>0</testcase><testcase classname="ButtonWithSpinnerTest view initModel root element" name="is a button with proper class" time="0.003"/><testcase>8</testcase><testcase classname="ButtonWithSpinnerTest view with spinner root element when initialState" name="does not have processing class" time="0"/><testcase>16</testcase><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 01-01-2016] and [age category = Child] [without] errors" time="0.001"/><testcase>24</testcase><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 01-01-1999] and [age category = Adult] [without] errors" time="0.002"/><testcase>2</testcase><testcase classname="ButtonWithSpinnerTest view initModel root element" name="does not have processing class" time="0.003"/><testcase>10</testcase><testcase classname="ButtonWithSpinnerTest view with spinner and processing and disabled state spinner container" name="has inner HTML with spinner itself (as SVG)" time="0.002"/><testcase>18</testcase><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 02-01-2012] and [age category = Child] [without] errors" time="0.001"/><testcase>1</testcase><testcase classname="ButtonWithSpinnerTest view initModel root element" name="does not have the spinner container" time="0.002"/><testcase>9</testcase><testcase classname="ButtonWithSpinnerTest view with spinner and processing and disabled state" name="is a button with proper classes and attributes" time="0.002"/><testcase>17</testcase><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 31-12-2012] and [age category = Child] [without] errors" time="0.001"/><testcase>25</testcase><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 01-01-2000] and [age category = Adult] [with] errors" time="0.002"/><testcase>3</testcase><testcase classname="ButtonWithSpinnerTest view with spinner and disabled state" name="is a button with proper classes and attributes" time="0.002"/><testcase>11</testcase><testcase classname="ButtonWithSpinnerTest view with spinner and processing and disabled state" name="has processing class" time="0"/><testcase>19</testcase><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 31-12-2011] and [age category = Child] [without] errors" time="0.001"/><testcase>4</testcase><testcase classname="ButtonWithSpinnerTest view with spinner and disabled state" name="does not have the spinner container" time="0.002"/><testcase>12</testcase><testcase classname="ButtonWithSpinnerTest view with spinner and processing state" name="is a button with proper classes and attributes" time="0.001"/><testcase>20</testcase><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 01-01-2011] and [age category = Child] [with] errors" time="0.001"/><testcase>5</testcase><testcase classname="ButtonWithSpinnerTest view with spinner and disabled state" name="does not have processing class" time="0.001"/><testcase>13</testcase><testcase classname="ButtonWithSpinnerTest view with spinner and processing state spinner container" name="has inner HTML with spinner itself (as SVG)" time="0.001"/><testcase>21</testcase><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 01-01-2011] and [age category = Junior] [without] errors" time="0"/><testcase>6</testcase><testcase classname="ButtonWithSpinnerTest view with spinner root element when initialState" name="is a button with proper classes and attributes" time="0.003"/><testcase>14</testcase><testcase classname="ButtonWithSpinnerTest view with spinner and processing state" name="has processing class" time="0"/><testcase>22</testcase><testcase classname="ConfirmationPassengerDetailsTest validateAgeCategoryChangeTest" name="validates person with [birthday = 02-01-2011] and [age category = Child] [with] errors" time="0.001"/></testsuite>
```

As you can see, `0.18.8` has things likes `<testcase>7</testcase>` all over - I assume this is an invalid JUnit format: http://help.catchsoftware.com/display/ET/JUnit+Format. `testcase` element's attributes `name`, `classname` and `time` are required, as far as I see. And anyway, what is this information for anyway?

**Comment by rtfeldman** [comment]
@NeverwinterMoon this is super helpful!

Would you mind opening a fresh issue for the invalid `<testcase>` situation? At this point we're onto a totally different issue from the original one in this thread. 😄

**Comment by NeverwinterMoon** [comment]
Created a separated issue for that: https://github.com/rtfeldman/node-test-runner/issues/218
