### ISSUE TITLE
Watch picks the wrong root directory, causing a crash in some cases

### ISSUE THREAD

**Issue by nonpop** [rtfeldman/node-test-runner#209]
When `Runner.findNearestElmPackageDir()` is given a path which does not end in a filename but a directory, it starts searching for elm-package.json one level too close to root (because of how `path.dirname()` seems to work), which causes the function to return a too general path. Now if this path happens to contain files inaccessible by the user, the whole thing crashes.

I don't know what a proper fix would look like but this fixed it for me:

```
diff --git a/lib/elm-test.js b/lib/elm-test.js
index c8cf691..d730604 100644
--- a/lib/elm-test.js
+++ b/lib/elm-test.js
@@ -327,7 +327,7 @@ function runElmTest() {
 
   testRootDir = path.resolve(Runner.findNearestElmPackageDir(testFilePaths));
   originalDir = path.resolve(
-    Runner.findNearestElmPackageDir([path.resolve(testRootDir, "..")])
+    Runner.findNearestElmPackageDir([path.resolve(testRootDir, "../dummyfile")])
   );
   elmPackagePath = path.resolve(path.join(testRootDir, "elm-package.json"));
```

**Comment by rtfeldman** [comment]
Fixed in 0.18.9!
