### ISSUE TITLE
Command line flags aren't validated

### ISSUE THREAD

**Issue by boxed** [rtfeldman/node-test-runner#211]
```
elm-test --asdkjasdjaslkdjasjldkj
```
just runs elm-test. It should complain that the flag is invalid/unknown. I discovered this when running

```
elm-test --add-dependencies
```
and it didn't do anything. I expected it to update tests/elm-packages.json or complain about a missing argument.

**Comment by harrysarson** [comment]
Would be great to check if elm-test still ignores invalid flags.

**Comment by boxed** [comment]
Yep. It's still broken in the same way.

**Comment by harrysarson** [comment]
Interesting, thank you @boxed!
