### ISSUE TITLE
Upgrade elm-test depndency range to include elm-test 4.2

### ISSUE THREAD

**Issue by jmedding** [rtfeldman/node-test-runner#220]
The latest tagged version (3.0.1) does not accept the latest version of elm-community/elm-test.

Would it be possible to issue a release with this dependency updated?

**Comment by jackfranklin** [comment]
@rtfeldman it would be great to get a release out, looks like there's been loads of improvements since the latest tagged release :) I'm more than happy to help with this and share the load if you need some extra hands!

**Comment by zwilias** [comment]
@jmedding the latest tagged version is actually 0.18.7.

If npm refuses to install that, you may attempt manually specifying that version - `npm i -g elm-test@0.18.7`

@jackfranklin [Join us on Slack](https://elmlang.herokuapp.com/)! ❤️

**Comment by jmedding** [comment]
@zwilias, I am trying to manage my elm test dependencies.  Elm package manager doesn't seem to recognize git tag 0.18.7, which does have the dependency I need.  If I specify "rtfeldman/node-test-runner": "4.0.0 <= v < 5.0.0", and then run `elm package install`, it wants to remove all of my packages.  Are you saying that if I install node-test-runner via npm, then elm package will find it?

**Comment by jmedding** [comment]
I tried installing as with `sudo npm i -g elm-test@0.18.7`

elm package install did not recognize this.  and wanted to remove all test packages, so I removed the line:
`"rtfeldman/node-test-runner": "4.0.0 <= v < 5.0.0"`, after which, I could get install the right elm test packages:

Here is the content of `exact-dependencies.json`

`{
    "elm-community/elm-test": "4.2.0",
    "elm-lang/virtual-dom": "2.0.4",
    "elm-lang/mouse": "1.0.1",
    "eeue56/elm-lazy": "1.0.0",
    "mgold/elm-random-pcg": "5.0.2",
    "eeue56/elm-lazy-list": "1.0.0",
    "elm-lang/dom": "1.1.1",
    "elm-lang/html": "2.0.0",
    "elm-community/json-extra": "2.3.0",
    "eeue56/elm-shrink": "1.0.0",
    "elm-lang/svg": "2.0.0",
    "elm-lang/core": "5.1.1"
}`

when I try to run elm test, I get the following error message: `I cannot find module 'Test.Runner.Node'.`

**Comment by jmedding** [comment]
It seems like we just need to publish 0.18.7 to the elm package directory, or am I missing something?

**Comment by zwilias** [comment]
Right, so, this may be where the confusion stems from - there are 2 things named "elm-test":
- `elm-community/elm-test` which is the Elm package that provides functions for writing tests and fuzz tests. Current version: 4.2.0
- `rtfeldman/node-test-runner` which is the npm `elm-test` package, and contains the executable runner. Current version: 0.18.7

Now, to make things confusing, a couple of versions ago, there was indeed a third thing involved - `rtfeldman/node-test-runner` _as an Elm package_. This is no longer required.

If you are starting from scratch:
- remove `elm-stuff`
- remove the `tests` directory
- `npm i -g elm-test`
- `elm-test init`

If you are starting from existing code, you may want to follow these instructions; https://github.com/rtfeldman/node-test-runner/blob/master/CHANGELOG.md#migrating-from-0182

Feel free to ping me on Slack if you get stuck!

**Comment by jmedding** [comment]
Ok - that was it.  I followed the migration instructions in the link and that worked.  I have to run elm-test as sudo the first time due to a file permission issue:

EACCES: permission denied, open '/home/me/myproject/assets/elm/elm-stuff/generated-code/elm-community/elm-test/src/Mainfb8d613309146e7847421bb92afda830.elm'

This is most likely because i had to use sudo to install with npm.  I can probably work this out though.
Thanks,

**Comment by zwilias** [comment]
Right. I'd highly recommend following the instructions here: https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory
