### ISSUE TITLE
Releases and changelog are behind

### ISSUE THREAD

**Issue by andys8** [rtfeldman/node-test-runner#223]
A minor, but easy to fix issue. The current released version is `0.18.9`.

But the latest tag/release is `0.18.7`
https://github.com/rtfeldman/node-test-runner/releases

The last version in the `CHANGELOG.md` is `0.18.8`
https://github.com/rtfeldman/node-test-runner/blob/master/CHANGELOG.md

And the `README.md` even prints:
<img width="213" alt="screen shot 2017-11-06 at 00 09 00" src="https://user-images.githubusercontent.com/13085980/32420202-c1a6a65a-c286-11e7-890a-4fbe61bc887f.png">
Okay, the last one wasn't serious.. ;)

**Comment by rtfeldman** [comment]
Got current with `0.18.11` - thanks!
