### ISSUE TITLE
Running tests is slow when there is no Internet connection

### ISSUE THREAD

**Issue by cheezy** [rtfeldman/node-test-runner#227]
When elm-test is run it requires an Internet connection.  You can see the code here:

https://github.com/rtfeldman/node-test-runner/blob/master/lib/elm-test.js#L501-L511

If you attempt to run your tests without Internet access you have to wait for the request to timeout. 
Here is the output from running `time elm-test` on my system:

Error: The following HTTP request failed.
<http://package.elm-lang.org/all-packages?elm-package-version=0.18&since=2017-11-29%2018%3A51%3A45.743255%20UTC>

FailedConnectionException "package.elm-lang.org" 80

Warning: Unable to complete missing packages check.
Error: The following HTTP request failed.
<http://package.elm-lang.org/all-packages?elm-package-version=0.18&since=2017-11-29%2018%3A51%3A45.743255%20UTC>

FailedConnectionException "package.elm-lang.org" 80

Warning: Unable to complete missing packages check.
Success! Compiled 0 modules.
Successfully generated /dev/null
Success! Compiled 1 module.
Successfully generated /Users/cheezy.morgan/dev/pragstudio-elm-code/finished-project/bingo/elm-stuff/generated-code/elm-community/elm-test/elmTestOutput.js

elm-test 0.18.10
----------------

Running 13 tests. To reproduce these results, run: elm-test --fuzz 100 --seed 1043401612

TEST RUN PASSED

Duration: 234 ms
Passed:   13
Failed:   0

real 1m1.176s
user 0m1.401s
sys 0m0.899s
 
It took over a minute to run 13 tests that take about 2 seconds when connected to the Internet.

Is there a way to add a flag to disable the Internet call?

**Comment by rtfeldman** [comment]
In general, I'd prefer to make things Just Work rather than adding flags...so #232 detects if you're offline and doesn't try to install packages if you are. 😄

**Comment by rtfeldman** [comment]
@cheezy See if this is still a problem on `npm install -g elm-test@beta` - should be fast now!
