### ISSUE TITLE
Make output coloring more legible

### ISSUE THREAD

**Issue by salutis** [rtfeldman/node-test-runner#229]
See the following `elm-test` output in Visual Studio Code's console:

<img width="211" alt="screen shot 2017-12-03 at 02 18 32" src="https://user-images.githubusercontent.com/1158274/33521370-687b0b84-d7d0-11e7-9b75-5c9e6e89c9d0.png">

I found it hard to read the `0` and `42`.

On a white background in macOS' Terminal, it's not much better:

<img width="235" alt="screen shot 2017-12-03 at 02 20 26" src="https://user-images.githubusercontent.com/1158274/33521373-8f651686-d7d0-11e7-9ef7-7328c1a7cb2d.png">

**Comment by zwilias** [comment]
Hah, @rtfeldman managed to fix this in b17cb63bea9aba1c7579453619c1cc2a0f6f47c6 before you created the ticket here :)

**Comment by rtfeldman** [comment]
@salutis Try it in the new 0.18.11 release - should be easier to read now!

<img width="908" alt="screen shot 2017-12-03 at 2 57 43 pm" src="https://user-images.githubusercontent.com/1094080/33530041-6e883fb6-d847-11e7-8f17-aecd05692c01.png">

**Comment by salutis** [comment]
I can confirm that 0.18.11 solved the problem. Thanks @rtfeldman and @zwilias!

**Comment by rtfeldman** [comment]
Thanks for reporting it!
