### ISSUE TITLE
Conflicts with "elm-github-install"

### ISSUE THREAD

**Issue by tjarratt** [rtfeldman/node-test-runner#237]
Hey friends, thank you so much for tirelessly working to produce a high-quality command line test runner for elm. Your work makes a world of a difference to me, as a simple work-a-day developer that occasionally writes some elm.

My issue isn't entirely clear to me, so I'm apologising upfront for not having as many details as I'd normally like. In brief, I'm finding that I'm having troubles getting `elm test` and `elm install` to play nicely together.

[elm-install](https://github.com/gdotdesign/elm-github-install) is a package installer that allows installing private repos, and from packages provided on github, that are not listed on elm-packages. Personally, I use this so that I can install [Elmer](https://github.com/brian-watkins/elmer) to write tests for my `view` and `update` functions.

In the past few releases of `elm-test`, I've noticed that I would see warnings about "Error: Your .elm/packages/ directory may be corrupted." when I ran `elm test`. Despite this, my tests still continued to work, and I thought nothing of it, since I had bigger fish to fry.

However, when I fresh installed `elm-test` on a new workstation today, I'm noticing that `elm test` actually treats this as an error now : "Warning: Unable to complete missing packages check - Command failed: elm-package install --yes". While it says "warning", this is actually an error, since my tests are not run, and `elm test` immediately exits with an error code.

For now, all I know is that I cannot use `elm-github-install` with `elm-test` version 0.8.12. 
However, if I downgrade `elm-test` to 0.8.7, I know that it will work.

Has there been any thought or discussion of how to handle cases such as this, or am I doing something exceptional and unsupported by `elm-test` ?

**Comment by mgold** [comment]
I'm in no position to fix it, but I think this is something elm-test should support.

**Comment by tjarratt** [comment]
For what it's worth, I'd be happy to contribute a fix if someone could explain to me what changed recently in `node-test-runner` and how we can reconcile the needs and values of these two projects for users ?

**Comment by avh4** [comment]
(I haven't caught up on the Elmer discourse thread yet, so maybe this has been mentioned ad nauseam already, but the thing that is unsupported by elm-test is installing private packages.  Elm 0.19 will supposedly remove the ability to use native code in private packages anyway, so be aware that you will need to have a migration plan if you plan to use Elm 0.19)

To the problem at hand, there are too many changes between elm-test 0.18.7 and 0.18.12, see https://github.com/rtfeldman/node-test-runner/compare/0.18.7...0.18.12.  **Can you narrow down the version where elm-test breaks for you?**

What does `elm-install` do?  elm-test should support projects that have an `elm-package.json` that correctly specifies dependencies and `source-directories`.  Is `elm-install` correctly setting those things for your project?

`elm-test` currently does strange things about how and where it copies and creates `.elm` files; I believe it currently does a mix of things that involve both `./elm-stuff` and `./tests/elm-stuff`, and possibly another `elm-stuff` folder thats nested somewhere in a folder inside of `./elm-stuff` that elm-test creates.  If there is indeed a problem with `elm-test`, I'd suspect it's related to how that all is handled.  (There have been recently changes to all that related to trying to improve rebuild speeds and robustness of watch mode.)

**Comment by zwilias** [comment]
I believe the change was introduced here: https://github.com/rtfeldman/node-test-runner/pull/232/files#diff-047f238be7300455dd55a8c22225e53fL502 (so cheap workaround: disable your internet ;) )

I don't feel like `elm-test` should support using a tool which makes `elm-package install` fail. However, I'm also not convinced that failure to run `elm-package install` when `elm-lang.org` successfully resolves needs to error out. Being able to resolve doesn't necessarily mean that it will respond as expected. If not all packages are installed, `elm-make` will either succeed if those packages aren't needed for the tests (i.e. not imported by any of the files imported by the tests) or fail if they really were needed. While failing early is nice, failing early when it might still succeed isn't great.

@rtfeldman thoughts?

**Comment by rtfeldman** [comment]
> am I doing something exceptional and unsupported by `elm-test`?

The short answer is yes. 😄

I really don't want to go down the rabbit hole of committing to `elm-test` supporting anything other than `elm-package`.

That said, @zwilias if you have a PR in mind that would make `elm-test` behave more reasonably in general when it can't reach `elm-lang.org`, and which also makes this issue moot, I'm game!

In the meantime I'm gonna close this issue (no offense, Tim!) just to be clear for future reference that we're not committing to support anything other than plain old `elm-package`.

**Comment by rtfeldman** [comment]
@tjarratt Separately, I'd love to hear what you're missing from current `elm-test`, as it would help us prioritize what things to add out-the-box! (Chat, Discourse, posting an issue - whatever's most convenient.)

**Comment by zwilias** [comment]
> That said, @zwilias if you have a PR in mind that would make elm-test behave more reasonably in general when it can't reach elm-lang.org, and which also makes this issue moot, I'm game!

Cool, #238!

**Comment by tjarratt** [comment]
Thanks for all the comments @avh4 @zwilias @rtfeldman - I appreciate the discourse, although I'm getting the impression that I've missed out on some zeitgeist or big huge Elm 0.19 discussion bandwagon that was happening outside of github 😞 .

@zwilias is 100% correct. Going and installing dependencies as part of `elm-test` is what effectively  makes this break for my use case. More specifically, checking the exit code of `elm-package` and halting the tests.

99% of the time I'm running tests and it is unnecessary to install packages, so this feels like a bit of a net loss for me, since now `elm-test` knows about running tests AND about possibly needing to install packages ? I'd be really, really curious about the design decision for this and understanding why `elm-test` needs to try to install packages when there is already a perfectly good command that does that.

In terms of a concrete proposal I'd be willing to suggest that I could implement a `--no-really-plz-dont-install-packages` flag for `elm-test` although to be 100% frank my preference would be to remove this feature entirely, or to have `elm-test` fail with a really nice error message if it appeared that packages had not been installed (say, perhaps, there was no `elm-stuff`, `packages` or `generated-code` directories).

**Comment by rtfeldman** [comment]
@tjarratt Try uninstalling and reinstalling with `npm install -g elm-test@beta` - it has @zwilias's PR in there!

**Comment by rtfeldman** [comment]
> 99% of the time I'm running tests and it is unnecessary to install packages (because they are already installed), so this feels like a bit of a net loss to me (personally), since now elm-test knows about running tests AND about possibly needing to install packages ? I'd be really, really curious about the design decision for this and understanding why `elm-test` needs to try to install packages when there is already a perfectly good command that does that.

That's a great point. 🤔

As I recall, one reason for doing this was to facilitate the `elm-stuff` hacks we do behind the scenes to make it so that you can pass `elm-test` a single file (or pattern of files) and have it run all the exposed tests.

However we've since evolved how we do that, and with the current symlink-based approach, the `elm-package install` step may have become unnecessary. I'm gonna open a new issue to discuss this.

**Comment by tjarratt** [comment]
Good context. I wasn't aware of those hacks, so that's pretty compelling (because users often want to run a single test as well, naturally).

I tried out the beta you linked, and I'm probably missing something *really* obvious here, but all I see is this error (even after uninstalling, reinstalling `elm-test` and even blowing away my local `elm-stuff` directories)...

```
-- NAMING ERROR - /usr/local/lib/node_modules/elm-test/src/Test/Reporter/Console.elm

Module `Test.Reporter.TestResults` does not expose `isTodo`

8| import Test.Reporter.TestResults as Results exposing (Failure, Outcome(..), SummaryInfo, TestResult, isTodo)
```

I double (and triple) checked the exports for `Test.Reporter.TestResults` and verified that `isTodo` is actually there... is this perhaps a known issue ?

**Comment by rtfeldman** [comment]
@tjarratt Hm, what happens if you set up a fresh project in a clean directory, do `elm-test init`, and try running tests there?
