### ISSUE TITLE
Watch mode improvements

### ISSUE THREAD

**Issue by zwilias** [rtfeldman/node-test-runner#242]
- [ ] **1**. #149 new/removed tests aren't picked up, and worse, throw an error
- [ ] **2**. #204 if initial compilation fails, `--watch` doesn't watch
- [ ] **3**. watch creates a new `new.Server` for every test run within a session
- [ ] **4**. filewatcher doesn't debounce and can trigger multiple testruns

I think a good way forward would be to make the supervisor have a single persistent `net.Server`, with the ability to `queue` testruns. This would be a first step towards taking care of point 4 and take care of point 3.

Untangling `generateAndRunTests` in `lib/elm-test.js` so that chokidar can do the filewatching independent of the compilation process would also be required. This would probably also involve making the `process.kill` at the end of the promise-chain in `lib/elm-test.js:runElmTest` check for `args.watch`. This would take care of points 1 and 2.

Finally, adding a `debounce` flag to the chokidar watcher would be the final piece to handling point 4; so that it's safer to switch branches with `elm-test --watch` running.

**Comment by harrysarson** [comment]
I had a go at some of these issues. I did not touch the `net.Server` stuff but I think I might have fixed 1, 2 and 3.

**Comment by harrysarson** [comment]
I believe these improvements have landed! Please do re-open (or make a new issue) if we can improve watch mode further!

**Comment by lydell** [comment]
@harrysarson It sounds like you intended to close this issue but forgot?
