### ISSUE TITLE
symlink problems

### ISSUE THREAD

**Issue by ericgj** [rtfeldman/node-test-runner#243]
Just to report, the fix for Windows at [this line](https://github.com/rtfeldman/node-test-runner/blob/87d8aa1b2805914da8f64e4005e5bf6ff9f8e06f/lib/elm-test.js#L362)  does not work if you're on a shared NTFS volume but on a VM -- on Archlinux I get a EROFS error (read only filesystem).  I wonder if there could be a command line switch for copying instead of symlinking?  Meanwhile I can work around it by copying it after it fails once, but it's pretty annoying.

**Comment by harrysarson** [comment]
I believe this is not an issue anymore!

I cannot find any evidence that we symlink (or use the `"junction"` option) in master.

![image](https://user-images.githubusercontent.com/16308754/52633535-a3e60180-2ebc-11e9-95ae-97fd186af45b.png)
![image](https://user-images.githubusercontent.com/16308754/52633546-af392d00-2ebc-11e9-913f-c8d738a5959c.png)

**Comment by lydell** [comment]
I don’t think this is an issue anymore either.
