### ISSUE TITLE
Non-determinism with --seed argument

### ISSUE THREAD

**Issue by mpizenberg** [rtfeldman/node-test-runner#248]
Hi, I was trying to reproduce a failed test and noticed some non-determinism in elm-test with a given seed. I did nothing at all (no file opening, no save, literally nothing) between the first run (no seed, with an error) and the second run (with provided seed). Yet, the second run does not reproduce the failed test.

If it helps, my configuration is:
- OS: 64-bit Archlinux, kernel version 4.9.77-1-lts
- Processor: i5-5300U
- elm stack: elm-make 0.18, elm-test 0.18.9, elm-community/elm-test 4.2.0, elm-lang/core 5.1.1
- node v9.2.1
- project: opensolid/geometry@29d9b1e1

The runs mentionned previously:

```
$ elm-test --fuzz 1000                                                                                                                3683ms  lun. 29 janv. 2018 11:18:32 +08
Success! Compiled 0 modules.
Successfully generated /dev/null
Success! Compiled 1 module.
Successfully generated /home/matthieu/git/perso/elm/packages/opensolid/geometry/elm-stuff/generated-code/elm-community/elm-test/elmTestOutput.js

elm-test 0.18.9
---------------

Running 183 tests. To reproduce these results, run: elm-test --fuzz 1000 --seed 221291260

↓ LineSegment2d
✗ Intersection should be symmetric

Given (LineSegment2d (Point2d (0.000001,10),Point2d (0.000001,-10)),LineSegment2d (Point2d (0,10),Point2d (0.0013658365545529956,-10)))

    Just (Point2d (9.999999999999997e-7,9.985356959488797))
    ╷
    │ Expect.equal
    ╵
    Just (Point2d (0.000001,9.985356959488797))



TEST RUN FAILED

Duration: 5876 ms
Passed:   182
Failed:   1

$ elm-test --fuzz 1000 --seed 221291260                                                                                                 8.4s  lun. 29 janv. 2018 11:18:43 +08
Success! Compiled 0 modules.
Successfully generated /dev/null
Success! Compiled 1 module.
Successfully generated /home/matthieu/git/perso/elm/packages/opensolid/geometry/elm-stuff/generated-code/elm-community/elm-test/elmTestOutput.js

elm-test 0.18.9
---------------

Running 183 tests. To reproduce these results, run: elm-test --fuzz 1000 --seed 221291260


TEST RUN PASSED

Duration: 5856 ms
Passed:   183
Failed:   0
```

**Comment by mgold** [comment]
Are you able to grab both copies of `elmTestOutput.js` and diff them?

**Comment by mpizenberg** [comment]
Yes I couldn't reproduce the exact same example, but this behavior happen quite often so here is the result of the diff with a new pair of (first error no seed, then give provided seed no error):

```
$ diff elmTestOutput_ko.js elmTestOutput_ok.js                                                                                         1.4m  mar. 30 janv. 2018 14:35:32 +08
28567c28567
< var _opensolid$geometry$Test_Generated_Main3149396508$main = A2(
---
> var _opensolid$geometry$Test_Generated_Main3486858469$main = A2(
28572c28572
<               seed: _elm_lang$core$Maybe$Nothing,
---
>               seed: _elm_lang$core$Maybe$Just(437228222),
29430,29432c29430,29432
< Elm['Test']['Generated']['Main3149396508'] = Elm['Test']['Generated']['Main3149396508'] || {};
< if (typeof _opensolid$geometry$Test_Generated_Main3149396508$main !== 'undefined') {
<     _opensolid$geometry$Test_Generated_Main3149396508$main(Elm['Test']['Generated']['Main3149396508'], 'Test.Generated.Main3149396508', undefined);
---
> Elm['Test']['Generated']['Main3486858469'] = Elm['Test']['Generated']['Main3486858469'] || {};
> if (typeof _opensolid$geometry$Test_Generated_Main3486858469$main !== 'undefined') {
>     _opensolid$geometry$Test_Generated_Main3486858469$main(Elm['Test']['Generated']['Main3486858469'], 'Test.Generated.Main3486858469', undefined);
29468c29468
< var initialSeed = null;
---
> var initialSeed = 437228222;
```

The pair of runs was:

```
$ elm-test --fuzz 1000
...
Running 183 tests. To reproduce these results, run: elm-test --fuzz 1000 --seed 437228222
...
TEST RUN FAILED
...
```

Directly followed by:
```
$ elm-test --fuzz 1000 --seed 437228222
...
Running 183 tests. To reproduce these results, run: elm-test --fuzz 1000 --seed 437228222
TEST RUN PASSED
...
```

**Comment by mgold** [comment]
Hmm, nothing too unexpected there. It's possible the seed to try is being output incorrectly in the first run.

Does it only happen with `--fuzz 1000`?

**Comment by mpizenberg** [comment]
No this isn't specific to `--fuzz 1000` it's just that I get an error faster but it happens also with any number.

> It's possible the seed to try is being output incorrectly in the first run.

Is there anything I could do to help verify this hypothesis?

**Comment by mgold** [comment]
> Is there anything I could do to help verify this hypothesis?

If you run the command with `--seed` multiple times is it consistent? But other than that, you'd need a way to look at a part of the internal state of the test runner.

**Comment by mpizenberg** [comment]
I spend some time digging into the code and I think the issue is with the way the supervisor is handling multiple processes. I modified `App.initOrUpdate` to debug log `numericSeed`, and modified `elm-test.js` to compile in debug mode -> Something weird happened: it logged 4 times the value. Turns out that the Main generated is called n times if I have n threads available.

When I set `var processes = 1` in `elm-test.js` instead of `Math.max(1, os.cpus().length)`, everything is back to normal: `run` is called only once and the seed displayed by first run is the correct one for reproductibility.

I've no idea how the code of `Supervisor.run` handles multiple processes, but I guess the error can be of two types:
1. Either the issue is the fact that the supervisor is launching an independent Main in each process.
2. Or this is fine, but then the issue is that the initial seed should not be generated inside a Main (after first update currently) but before job distribution by the supervisor.

Hope this will help solve the issue with multiple processes. Would be a shame to restrict to one process because of non-reproductibility with multiple processes.

**Comment by zwilias** [comment]
Yeah, your analysis is correct - n processes are spawned (one for each logical core) and they should _in theory_ receive work in a deterministic manner.

So if I had to guess, I'd say it's more likely something to do with (2). Perhaps the initial seed should be passed from JS, always. Something like `Math.floor(Math.random() * 0xFFFFFFFF)` should suffice. It would also allow cleaning up some of the stuff that deals with the possibility off `initialSeed` being `Nothing`. It would be interesting to try and write a failing test for this scenario 😅

**Comment by mpizenberg** [comment]
If we want to generate `initialSeed` from JS side, the part that would have to be changed in JS side is located in the function `generateAndRunTests` (`elm-test.js`):
```js
  var fuzz = parseInt(args.fuzz);
  var seed = parseInt(args.seed);
  var opts = {
    fuzz: isNaN(fuzz) ? "Nothing" : "Just " + fuzz,
    seed: isNaN(seed) ? "Nothing" : "Just " + seed,
    report: getReportCode(),
    paths: filePathArgs.map(sanitizedToString).join(",")
  };

  var optsCode =
    "{ runs = " +
    opts.fuzz +
    ", report = " +
    opts.report +
    ", seed = " +
    opts.seed +
    ", processes = " +
    processes +
    ", paths = [" +
    opts.paths +
    "]}";
```

I noticed also that `args.seed` is used later to create a variable `initialSeed` still on JS side that seems to be dead code. This variable ends as a flag for the worker program, but the flags are not used in `App.run` (`init args = ...` where `args` is not used).

```js
// in runTests(testFile)
var initialSeed = (args.seed === undefined) ? null : args.seed;
prepareCompiledJsFile(initialSeed, report, dest);

// in prepareCompiledJsFile(initialSeed, report, dest)
var finalContent = [
  // ...
  "var initialSeed = " + String(initialSeed) + ";",
  // ...
  after
].join("\n");

// imported from file templates/after.js
var potentialModuleNames = Object.keys(Elm.Test.Generated);
var testModule = Elm.Test.Generated[potentialModuleNames[0]];
var app = testModule.worker({ seed: initialSeed, report: report });
// there is the start of the app with provided flags
```

**Comment by lydell** [comment]
#465 implements even stronger guarantees around seed always being defined
