### ISSUE TITLE
Recommend local rather than global install

### ISSUE THREAD

**Issue by RGBboy** [rtfeldman/node-test-runner#249]
I ran into an interesting problem where I wanted to run the tests of an existing elm library that had been set up to work with the previous version of `elm-test` but, because I had installed the latest version globally, was getting errors when trying to test. I have a good understanding of node and NPM so I was able to figure out the issue, however others may not be. I wonder if it would be better to recommend users to:

* Install this npm package locally and set up a local package.json file to document the version installed.
* Recommend consumers document how to run tests in their readme file.

Examples of the above could be provided here to make setting up elm test simple.

**Comment by RGBboy** [comment]
Also note that https://github.com/elm-community/elm-test currently recommends the global install too.

**Comment by Razzeee** [comment]
Hrm `npx elm-test` seems to work flawless for me.

**Comment by RGBboy** [comment]
@Razzeee here is a project that I have elm-test setup locally: https://github.com/RGBboy/websocket-server. Essentially set it up as a node project too and add elm-test as a development dependency (`npm install elm-test --dev`). When you install node packages, it makes the `{project}/node_modules/.bin` available on the path when the current working directory is {project}. This means you have access to the local `elm-test` command.

I would structure it slightly differently now as the latest elm-test expects a test folder in the root of your project.
