### ISSUE TITLE
0.19: fails on linux if --compiler is set

### ISSUE THREAD

**Issue by avh4** [rtfeldman/node-test-runner#261]
From https://elmlang.slack.com/archives/C13L7S5GR/p1529332908000221

On `av-0.19` branch, PR #257  this line:
```
output = output.replace(/^elm:.*no version information available \(required by elm\)\n/, '');
```
is assuming a hardcoded compiler path of `elm`.  Filtering out that line needs to work if `--compiler` is passed with something different.

(Or, a better fix is is `elm` stops printing the report JSON to stderr so that we don't have to filter any more.)

**Comment by harrysarson** [comment]
I grepped the code base for both `"replace"`and `"output"`. I could not find anything like this so I am going to hope that we have managed to fix this without realizing! @avh4 do you know how I can confirm this is fixed?

**Comment by avh4** [comment]
That error message was about this sort of thing: https://stackoverflow.com/questions/137773/what-does-the-no-version-information-available-error-from-linux-dynamic-linker  

So I guess it must have been after that that Elm 0.19 switch to publishing static linux binaries?  I would expect this message will no longer be produced when using statically-linked elm binaries.

**Comment by harrysarson** [comment]
Makes sense! I think the js in this repository that handled this find and replace on the error output has been removed? The slack archives are long gone, could you point me to where the js code was/is?

**Comment by harrysarson** [comment]
I am happy/confident this is fixed!
