### ISSUE TITLE
Non helpful error message with typo in elm.json

### ISSUE THREAD

**Issue by kuon** [rtfeldman/node-test-runner#271]
My `elm.json` had a typo:

```json
    "test-dependencies": {
        "elm-exploration/test": "1.0.0 <= v < 2.0.0"
    }
```

Forgot an `s` at the end of `elm-explorations`. The error message from `elm-test` could be improved:

    elm-test internal error: got an unexpected result from 'elm make' when validating transitive dependencies.  Please report this at https://github.com/rtfeldman/node-test-runner/issues

**Comment by lydell** [comment]
This is what it looks like on master:

```
❯ elm-test
Failed to run `elm-json solve`:

-- NO VALID PACKAGE VERSION ----------------------------------------------------

Because elm-exploration/test does not appear to exist and this project depends
on elm-exploration/test 1.2.0, no valid set of package versions could be found.
```
