### ISSUE TITLE
ECONNRESET when run on travis

### ISSUE THREAD

**Issue by kuon** [rtfeldman/node-test-runner#272]
This might not be a `node-test-runner` issue, but as it started appearing with the elm `0.19` upgrade, it might be.

Relevant build failure (tried multiple times, and it always fails with this error):

https://travis-ci.org/kuon/elm-hsluv/builds/421126000

**Comment by rtfeldman** [comment]
It sounds most likely to be a Travis issue...

Does this happen with the current beta of `elm-test`?

**Comment by kuon** [comment]
Yes, still crashing with beta9.

https://api.travis-ci.org/v3/job/429110817/log.txt

**Comment by rtfeldman** [comment]
Can you make a SSCCE?

I haven't heard of anyone else running into this, which suggests it might be specific to your setup... 😅

**Comment by kuon** [comment]
I tried everything to make an SSCCE but I cannot reproduce the error outside my package.

**Comment by kuon** [comment]
This is now fixed by elm `0.19.0-bugfix6` and this package `0.19.0-rev6`.
