### ISSUE TITLE
Highlighting Expect.equal diff for large data-structures results in hang

### ISSUE THREAD

**Issue by stephenreddek** [rtfeldman/node-test-runner#280]
Running elm-test with the console reporter with a failing test that uses `Expect.equal` on two large data-structure hangs.

I tested with this quickly (filled the list to be about 400 elements each):
```
module SSCCE exposing (suite)

import Expect
import Test exposing (..)


testLarge : Test
testLarge =
    test "foo bar" <|
        \() ->
            Expect.equal
                [ { foo = "foo", bar = "baz" }
                , { foo = "foo", bar = "bar" }
                ⋮ 
                ]
                [ { foo = "foo", bar = "bar" }
                , { foo = "foo", bar = "bar" }
                ⋮ 
                ]

```

It appears to me that the issue is with the `Diff` just taking too long to run. If you use the junit or json reporter, the tests run quickly.

One solution would be to check the length of the string prior to running the diff in the [formatter](https://github.com/rtfeldman/node-test-runner/blob/master/src/Test/Reporter/Console/Format.elm#L82) - similar to how it doesn't diff floats or empty strings.

**Comment by rtfeldman** [comment]
https://github.com/rtfeldman/node-test-runner/pull/319 may have fixed this.

**Comment by stephenreddek** [comment]
I apologize for my long delay in responding. This now resolved (tested on0.19.0-rev4). Thank you!
