### ISSUE TITLE
0.19.0-beta9 freezes on Linux CI

### ISSUE THREAD

**Issue by Y0hy0h** [rtfeldman/node-test-runner#288]
I didn't pin the `elm-test` version on my CI, and thus tested the fresh `0.19.0-beta9` update. Unfortunately, the tests [simply freeze after the statement on how to reproduce the tests](https://travis-ci.org/Y0hy0h/breakdown/builds/428983514#L686).

I reverted to `0.19.0-beta8` in [this PR](https://github.com/Y0hy0h/breakdown/pull/39) and it works again.

Before that, I tried:

- Resetting all caches (did not work)
- Executing `0.19.0-beta9` locally on Windows (worked!)

I'm completely unsure what the issue is and whether it might be something in my (unusual) setup. So please consume this issue with a pinch of salt (as Germans like to say).

**Comment by rtfeldman** [comment]
Seems to be Linux-specific: https://travis-ci.org/rtfeldman/node-test-runner/builds/429400712

**Comment by Y0hy0h** [comment]
I added to the description that I tested this locally on Windows and it worked.

**Comment by duncanmalashock** [comment]
I ran into this also:
```
The command "elm-format --validate src --elm-version=0.19" exited with 0.
$ elm-test --verbose
Running elm make /home/travis/build/battermann/Tonal/tests/PlaceholderTests.elm --output /dev/null
Running elm make /home/travis/build/battermann/Tonal/elm-stuff/generated-code/elm-explorations/test/src/Test/Generated/Main2921126987.elm --output /home/travis/build/battermann/Tonal/elm-stuff/generated-code/elm-explorations/test/elmTestOutput.js
elm-test 0.19.0-beta9
---------------------
Running 1 test. To reproduce these results, run: elm-test --fuzz 100 --seed 100716193812984 /home/travis/build/battermann/Tonal/tests/PlaceholderTests.elm
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by magopian** [comment]
Can confirm that I had the same issue, and that downgrading to beta8 fixed it!

**Comment by duncanmalashock** [comment]
> Can confirm that I had the same issue, and that downgrading to beta8 fixed it!

The downgrade worked for me too

**Comment by rtfeldman** [comment]
@Y0hy0h @duncanmalashock @magopian What CI system are you using?

I've been unable to reproduce this on any local Linux environment, but it reporduces 100% on Travis CI.

**Comment by duncanmalashock** [comment]
I was using Travis

**Comment by Libbum** [comment]
Happened to me using Arch.

**Comment by magopian** [comment]
Travis also

**Comment by kazk** [comment]
@rtfeldman

`elm-test` is creating `48` workers on Travis and those are preventing the Node process to exit.

https://github.com/rtfeldman/node-test-runner/blob/f273e23bb20c49bf252cf3967e6533542663788e/lib/elm-test.js#L65

https://github.com/rtfeldman/node-test-runner/blob/f273e23bb20c49bf252cf3967e6533542663788e/lib/supervisor.js#L217-L218

To confirm this, I made the following changes:
```diff
- var processes = Math.max(1, os.cpus().length);
+ const isCI = process.env.CI === "true";
+ var processes = Math.max(1, isCI ? 4 : os.cpus().length);
```
and [`tests/ci.js` no longer hangs](https://travis-ci.org/kazk/node-test-runner/jobs/438453448).
The test for `--watch` in `tests/flags.js` is broken (`Unexpected non-json output`) and sometimes causes prevents Mocha from exiting, but that should be a separate issue.

I think `libsysconfcpu` used to prevent this from happening.

**Comment by kazk** [comment]
I'm not sure why `beta8` works. Maybe something in https://github.com/rtfeldman/node-test-runner/commit/c123c82f7cf68acd8230b1fc9a06e51541e3e83f made this more significant.

I used [why-is-node-running](https://www.npmjs.com/package/why-is-node-running) on `lib/elm-test.js` to find this and the output is:
```
There are 48 handle(s) keeping the process running
# Timeout
/home/travis/build/kazk/node-test-runner/lib/elm-test.js:3 - setTimeout(function () {
# PIPEWRAP
/home/travis/build/kazk/node-test-runner/lib/Compile.js:75                           - process.stdin,
/home/travis/build/kazk/node-test-runner/node_modules/node-elm-compiler/index.js:63  - return options.spawn(pathToElm, processArgs, processOpts);
/home/travis/build/kazk/node-test-runner/node_modules/node-elm-compiler/index.js:102 - return runCompiler(sources, optionsWithDefaults, pathToElm)
/home/travis/build/kazk/node-test-runner/lib/Compile.js:46                           - const compileProcess = elmCompiler.compile(testFilePaths, {
/home/travis/build/kazk/node-test-runner/lib/Compile.js:40                           - return new Promise((resolve, reject) => {
/home/travis/build/kazk/node-test-runner/lib/elm-test.js:325                         - return Compile.compileAll(testFilePaths, generatedCodeDir, args.verbose, pathToElmBinary, args.report)
/home/travis/build/kazk/node-test-runner/lib/elm-test.js:364                         - var currentRun = run();
/home/travis/build/kazk/node-test-runner/bin/elm-test:3                              - require("../lib/elm-test.js");
# PIPESERVERWRAP
/home/travis/build/kazk/node-test-runner/lib/supervisor.js:257 - server.listen(pipeFilename);
/home/travis/build/kazk/node-test-runner/lib/supervisor.js:20  - return new Promise(function(resolve, reject) {
/home/travis/build/kazk/node-test-runner/lib/elm-test.js:180   - return Supervisor.run(
# PROCESSWRAP
/home/travis/build/kazk/node-test-runner/lib/supervisor.js:218 - var worker = child_process.fork(dest);
/home/travis/build/kazk/node-test-runner/lib/supervisor.js:217 - workers = _.range(0, processes).map(function(index) {
# PIPEWRAP
/home/travis/build/kazk/node-test-runner/lib/supervisor.js:218 - var worker = child_process.fork(dest);
/home/travis/build/kazk/node-test-runner/lib/supervisor.js:217 - workers = _.range(0, processes).map(function(index) {
# PROCESSWRAP
/home/travis/build/kazk/node-test-runner/lib/supervisor.js:218 - var worker = child_process.fork(dest);
/home/travis/build/kazk/node-test-runner/lib/supervisor.js:217 - workers = _.range(0, processes).map(function(index) {
...
```
The first `Timeout` is what I added to call this module so can be ignored.

**Comment by Y0hy0h** [comment]
Thank you! That looks like it was a very nasty bug. So thanks for grinding through it!
