### ISSUE TITLE
Collocate tests with src

### ISSUE THREAD

**Issue by sporto** [rtfeldman/node-test-runner#291]
Now that Elm 0.19 has "test-dependencies" I wonder if it would possible to collocate the test with the source code. E.g.

```
src/User.elm
src/User.test.elm (or UserTest.elm)
```

Having the test close to the code is much nicer, as you can find it quickly and is easier to maintain.

In our code we do this by having a `tests/Main.elm` that imports all the test files from `src`. But this isn't great as it is easy to forget importing one.

Thanks

**Comment by sporto** [comment]
Partially. Why behave in a different way with packages? I think it will be nicer if we can collocate the test in applications and packages.

**Comment by lydell** [comment]
On master (and maybe even 0.19.1-revision4) it’s possible to colocate tests in `src/` even for packages.
