### ISSUE TITLE
Clear screen in watch mode

### ISSUE THREAD

**Issue by jackfranklin** [rtfeldman/node-test-runner#296]
A small feature request that I'd be very happy to PR if you'd like it - I find it useful how Jest clears the screen before each watch test run, so you don't have to always end up looking at the bottom of your terminal.

I think we could steal the clearing logic from Jest and insert it into the test runner. Happy to work on it if you'd like it :)

**Comment by mgold** [comment]
It shouldn't be hard to shell out to `clear`.

**Comment by rtfeldman** [comment]
@jackfranklin yeah, sounds good! I like that idea.

Feel free to PR it!
