### ISSUE TITLE
Set up prettier + eslint

### ISSUE THREAD

**Issue by jackfranklin** [rtfeldman/node-test-runner#310]
Hey @rtfeldman , would you have any objection to me setting up Prettier and/or ESLint with some reasonable rules (that this project would mostly pass)? I think it would make contributing much easier :)

**Comment by rtfeldman** [comment]
Sure, go for it!

**Comment by harrysarson** [comment]
I think this can be closed as #314 is merged!

**Comment by harrysarson** [comment]
Actually eslint hasn't been added yet so we can leave open.

**Comment by lydell** [comment]
ESLint was added in https://github.com/rtfeldman/node-test-runner/pull/425 🎉
