### ISSUE TITLE
Tests pass and then hang on Appveyor CI

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/node-test-runner#311]
Not sure why this might be, but it seems to be platform-specific. They pass and then exit on Travis!

**Comment by kazk** [comment]
I've accidentally fixed this in #312.

![image](https://user-images.githubusercontent.com/639336/47591083-45a00d80-d923-11e8-9daa-6cd6bf3b4275.png)

**Comment by rtfeldman** [comment]
> I've accidentally fixed this

😂 

Thanks so much @kazk!
