### ISSUE TITLE
Watch mode ignores Ctrl+C in Windows

### ISSUE THREAD

**Issue by Y0hy0h** [rtfeldman/node-test-runner#313]
When running tests in watch mode, they will execute properly. However, the process will not respond to <kbd>Ctrl</kbd>+<kbd>C</kbd>, so terminating it is impossible. (Except by closing the terminal.)

This was last tested on 31238c8a475ded716d2bb9431d1e9ecc3b2081f6, see https://github.com/rtfeldman/node-test-runner/pull/309#issuecomment-433157279 for more details.

**Comment by rtfeldman** [comment]
Seems to work ok on macOS; presumably the issue only affects Windows!

**Comment by harrysarson** [comment]
I cannot reproduce on either cmd or powershell with both 31238c8 or the latest version on npm.

**Comment by Y0hy0h** [comment]
I also cannot reproduce this anymore with `elm-test@0.19.0-rev4`.
