### ISSUE TITLE
Proposal for adding a random seed for property based tests

### ISSUE THREAD

**Issue by robertjlooby** [rtfeldman/node-test-runner#32]
When using `elm-check` with `elm-test`, the last argument to `Check.Test.test` is a `Random.Seed`. If running the tests inside a custom handler one could do something like

```
seed : Random.Seed
seed = Random.initialSeed initialSeed

port initialSeed : Int
```
in the `Main` module and then do
```
Elm.worker( Elm.Main, { initialSeed: Date.now() } )
```
to run the tests with a random initial seed value. It would be nice to be able to do something similar when using the `elm-test` package. Currently the initial value can't be set randomly so every run is the same. I imagine this would have to done thorough a flag so that it wouldn't _require_ the port to be declared. So the API could for example be:
```
elm-test TestRunner.elm // normal test suite, no port
elm-test --seed TestRunner.elm // would require a seed port, pass in current time
elm-test --seed=1234 TestRunner.elm // allow passing in a seed value to recreate failing run
```
Thoughts?

**Comment by rtfeldman** [comment]
I am totally in favor of this, and it's planned for the revamped `elm-test` (currently underway, but early in the process)

**Comment by rtfeldman** [comment]
Added in #61
