### ISSUE TITLE
validating transitive dependencies - elm/file

### ISSUE THREAD

**Issue by doanythingfordethklok** [rtfeldman/node-test-runner#320]
I get this error when attempting to run tests on a package that includes `elm/file` as a dependency. 

```
elm-test internal error: got an unexpected result from 'elm make' when validating transitive dependencies.  Please report this at https://github.com/rtfeldman/node-test-runner/issues
```

UPDATE: I was able to resolve the above error by updating peer dependencies of elm/file like this.

```
"dependencies": {
        "elm/core": "1.0.1 <= v < 2.0.0",
        "elm/file": "1.0.0 <= v < 2.0.0",
        "elm/json": "1.1.0 <= v < 2.0.0"
    },
```

Now this is the error:

`This test failed because it threw an exception: "ReferenceError: File is not defined"`

**Comment by SidneyNemzer** [comment]
Regarding `ReferenceError: File is not defined`, see https://github.com/elm/core/issues/1002

**Comment by doanythingfordethklok** [comment]
I upgraded elm/core and the tests are now working. Thank you for the quick fix.  :)
