### ISSUE TITLE
The dependencies in your elm.json are not compatible.

### ISSUE THREAD

**Issue by joecorkerton** [rtfeldman/node-test-runner#323]
Just installed the elm-test cli via npm and ran `elm-test init`, and am now getting the following error.

`The dependencies in your elm.json are not compatible.`

I have not edited my elm.json by hand and my actual code compiles fine using `elm make`.

elm-test version 0.19.0-rev3

My elm.json:

```
{
    "type": "application",
    "source-directories": [
        "src"
    ],
    "elm-version": "0.19.0",
    "dependencies": {
        "direct": {
            "elm/browser": "1.0.1",
            "elm/core": "1.0.2",
            "elm/file": "1.0.1",
            "elm/html": "1.0.0",
            "ericgj/elm-csv-decode": "2.0.1",
            "lovasoa/elm-csv": "1.1.5",
            "mdgriffith/elm-ui": "1.1.0"
        },
        "indirect": {
            "elm/bytes": "1.0.3",
            "elm/json": "1.1.1",
            "elm/regex": "1.0.0",
            "elm/time": "1.0.0",
            "elm/url": "1.0.0",
            "elm/virtual-dom": "1.0.2"
        }
    },
    "test-dependencies": {
        "direct": {
            "elm-explorations/test": "1.2.0"
        },
        "indirect": {
            "elm/random": "1.0.0"
        }
    }
}
```

**Comment by nonpop** [comment]
I have a similar problem, it complaining about indirect dependencies. My guess is that when Test.Html was added, elm-test init/install wasn't made aware of that or something, so it doesn't create the correct indirect test-dependencies. I might examine more closely when I have time.

**Comment by nonpop** [comment]
Are you using vscode with the elm extension version 0.23.0? Because in my case, the problem appeared after changing files when running `elm-test --watch`, and I noticed the problem went away when I tried with vim. Then I tried to downgrade the extension to 0.22.0 and now it seems to work as it should again.

**Comment by joecorkerton** [comment]
I am using vscode, but never ran `elm-test --watch`, so would be surprised if it was caused by the extension. Can try it out though

**Comment by MohammedSheikhIbrahim** [comment]
Also experiencing the same issue. I don't even use VSCode; I use Atom.
