### ISSUE TITLE
Fails to run when libc is not present due to incorrectly compiled/distributed dep

### ISSUE THREAD

**Issue by lpil** [rtfeldman/node-test-runner#324]
Related issue: https://github.com/elm-explorations/test/issues/31

When running `elm-test` on my CI running alpine Linux it fails like so:

```
$ elm-test
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /opt/app/waive/assets/node_modules/elmi-to-json/unpacked_bin/elmi-to-json ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

Exited with code 1
```

I connect and check that file it does exist and has the right permissions, but attempting to run it results in `bash: /opt/app/waive/assets/node_modules/elmi-to-json/unpacked_bin/elmi-to-json: No such file or directory`.

I believe this is due to Alpine Linux's use of musl over libc. The elmi-to-json binary is not statically linked and assumes that libc is present, so it cannot be run.

It's common to use Alpine Linux when using Docker as it currently provides the smallest images available, so it would be beneficial for `elm-test` to work on this distribution.

**Comment by bowsersenior** [comment]
I think this will be solved just by bumping the required version of `elmi-to-json` to `0.19.2`. However, the latest version of `elmi-to-json` on npm is `0.19.1`. Seems like this issue needs to be resolved firs to publish the newest version to npm:
* https://github.com/stoeffel/elmi-to-json/issues/23

**Comment by lpil** [comment]
Yup! I'm the one attempting to statically link that binary! If you much about Haskell build tooling help would be welcomed

**Comment by bowsersenior** [comment]
I may have a fix, please look at this PR:

* https://github.com/stoeffel/elmi-to-json/pull/25

**Comment by bowsersenior** [comment]
I opened a PR to upgrade elmi-to-json to 0.19.3 and fix this issue: https://github.com/rtfeldman/node-test-runner/pull/358

**Comment by lpil** [comment]
Thank you! :)
