### ISSUE TITLE
Update node-elm-compiler dependency to fix lodash vulnerability

### ISSUE THREAD

**Issue by janslifka** [rtfeldman/node-test-runner#342]
There was a recent fix for lodash security vulnerability (https://github.com/rtfeldman/node-test-runner/pull/340). However, this package depends on `"node-elm-compiler": "5.0.1"` which uses the previous version of lodash.

It seems like the lodash version was fixed in  `"node-elm-compiler": "5.0.2"`, so I suppose updating it in this package should resolve the issue?

**Comment by mgold** [comment]
Was this not fixed by #340?

**Comment by janslifka** [comment]
Not really, you can reproduce the issue in empty npm project with
```
$ npm install -D elm-test
$ npm audit
```

And you can see that there's still an issue with lodash:

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ elm-test [dev]                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ elm-test > node-elm-compiler > lodash                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/782                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

You can use `npm list lodash` to see where the problem comes from.

```
└─┬ elm-test@0.19.0-rev5
  ├─┬ elmi-to-json@0.19.1
  │ └─┬ binwrap@0.2.0
  │   └─┬ request-promise@4.2.4
  │     └─┬ request-promise-core@1.1.2
  │       └── lodash@4.17.11  deduped
  ├── lodash@4.17.11
  └─┬ node-elm-compiler@5.0.1
    ├─┬ find-elm-dependencies@2.0.0
    │ └── lodash@4.17.10
    └── lodash@4.17.10
```

The old version of lodash comes through `node-elm-compiler@5.0.1`. It is updated in `node-elm-compiler@5.0.2` though.

**Comment by harrysarson** [comment]
Maybe we could use the help of https://greenkeeper.io/. I help maintain math.js and we have found greenkeeper very helpful there :)

**Comment by mgold** [comment]
@janslifka Okay, thanks for the detailed information.
