### ISSUE TITLE
Error if run from a subdirectory

### ISSUE THREAD

**Issue by harrysarson** [rtfeldman/node-test-runner#355]
### To reproduce this error

In an empty directory run

1. `$ elm init`
1. `$ elm-test init`
2. `$ cd tests`
3. `$ elm-test`

### Output

```
Error reading elm.json: Error: ENOENT: no such file or directory, open '/media/harry/WINDOWS/Users/harry/elm/test-example/tests/elm.json'
```

---
OS: ubuntu
All the elm-test versions 0.19.0 and later have this bug.

**Comment by lydell** [comment]
For anyone how would like to pick this up:

The commands that need `elm.json` assert that an `elm.json` exists in the current working directory:

https://github.com/rtfeldman/node-test-runner/blob/2e2fd090837177f89218e2a4096dce4ea4d91e14/lib/elm-test.js#L380-L389

Those commands should take an elmJson as input instead. Then we could replace the `assertElmJsonInCwd` function with a function that finds the first `elm.json` upwards in the folder hierarchy (passing it on to the commands that need it), or errors saying that no `elm.json` could be found.
