### ISSUE TITLE
Watch mode fails with SyntaxError

### ISSUE THREAD

**Issue by andys8** [rtfeldman/node-test-runner#357]
I start elm-test in watch mode and get this error a lot lately, when writing (constantly changing) a test. The interrupting thing is, that `elm-test` will end working and I have to restart it manually again. It happens every 1 or 2 minutes. Can I provide more information to make this easier to reproduce?

### Error message

```shell
MainTest.elm changed. Rebuilding!
Received invalid JSON from test interface search: SyntaxError: Unexpected token e in JSON at position 0
```

### Versions

```shell
elm-test --version
0.19.0-rev6

node -v
v11.14.0
```

[elm.json](https://github.com/andys8/vim-emulation/blob/master/elm.json)

Related issues: See #235

**Comment by harrysarson** [comment]
I believe this is an error caused by `elmi-to-json` producing invalid output - or elm-test incorrectly parsing the output. May be wrong though.

**Comment by andys8** [comment]
We could update `elmi-to-json` to 0.19.2 [when it's published to npm](https://github.com/stoeffel/elmi-to-json/issues/26), but the changes don't like like they would fix the issue.

**Comment by harrysarson** [comment]
A good first step would be a more informative error message, ideally including the output of  `elmi-to-json`

**Comment by andys8** [comment]
Relevant (but doesn't necessary fix the issue) #358

**Comment by ygrenzinger** [comment]
Hello,

I have just started my exploration of Elm and trying to do tests with elm-test, I fall into the same error running only `elm-test`

I have just done  `elm-test init` before.

Node 12.10.0 
Npm 6.11.3

Do you need a repo or more information ?

**Comment by harrysarson** [comment]
What is the output of `elm --version`?

**Comment by ygrenzinger** [comment]
@harrysarson  elm is 0.19.0
Maybe this version is breaking too much things ?

Btw I have this : npm WARN deprecated fsevents@1.2.4: Way too old
And many following warning / error but it seems it's an unrelated problem.

**Comment by ygrenzinger** [comment]
@harrysarson oh it works with elm-test 0.19.0-rev5 ... so the breaking part is somewhere in elm-test 0.19.0-rev6

**Comment by harrysarson** [comment]
@andys8 does this issue still occur? I am going to close preemptively, but only so that you can re-open if this is still an issue!

**Comment by andys8** [comment]
@harrysarson I'm not using Elm on a regularly basis as of today and therefore can't tell.

**Comment by harrysarson** [comment]
No worries! If you do find yourself using elm more regularly and the test runner starts giving you grief again you know what to do!
