### ISSUE TITLE
Didn't find my installed modules

### ISSUE THREAD

**Issue by jessitron** [rtfeldman/node-test-runner#36]
Once I added an import of my own source file, the compile of TestRunner failed. It didn't find the module Css (my project uses elm-css). 

My workaround is: `mv tests test` because then node-elm-test doesn't cd to tests, and then it can find the installed modules in elm-stuff.

I also added `test` as a source directory in elm-package.json. (And I had to manually install elm-test and elm-console packages, because init didn't add them to elm-package.json, but that's probably a separate issue)

**Comment by opsb** [comment]
I ran into this as well, my workaround was to simply copy my dependencies into tests/elm-package.json. Perhaps there's a better way to do this? If elm-package adds support for local dependencies then perhaps the nicest option would be to just point to the elm-package.json in the root from your tests/elm-package.json.

**Comment by rtfeldman** [comment]
In the next release, `elm-test init` will do this for you. Not a complete fix, but an improvement!

**Comment by opsb** [comment]
As the test dependencies should be a super set of the project's dependencies perhaps `elm-test sync-dependencies` could ensure that test's elm-package.json contains everything it needs?

**Comment by rtfeldman** [comment]
Yep! I called it `add-dependencies` since it only adds and never removes, but yeah that's in too. 😄

**Comment by opsb** [comment]
sweet!

**Comment by rtfeldman** [comment]
The functionality that's currently in beta is going to be the short-term fix for this. Longer-term, 0.19 should add a `test-dependencies` field to `elm-package.json`, which will give us a single source of truth as to which dependencies go where.
