### ISSUE TITLE
Received invalid JSON from test interface search: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by zkrzyzanowski** [rtfeldman/node-test-runner#383]
#### Steps to Reproduce
1. `elm-test app/elm-modules/*Test.elm`

#### Output
* `Received invalid JSON from test interface search: SyntaxError: Unexpected end of JSON input`

#### Versions
```
elm --version
0.19.0

elm-test --version
0.19.0-rev6

node -v
v10.15.3

```

This fails locally on my machine and in Travis where it was working previously in Travis at least. Not sure if it's related to [this](https://github.com/rtfeldman/node-test-runner/issues/258)

Thanks in advance!

**Comment by zkrzyzanowski** [comment]
Closing issue, running, `npm install npm@latest -g` and removing `elm-stuff` folder resolved the issue.

**Comment by r-k-b** [comment]
zkrzyzanowski's advice to update `npm` didn't work for me, but it led me to uninstalling then reinstalling `elm` and `elm-test` (all globally), which seems to have done the trick.

(I also deleted `elm-stuff` a number of times.)
