### ISSUE TITLE
Improve version naming scheme

### ISSUE THREAD

**Issue by andys8** [rtfeldman/node-test-runner#387]
The `-revX` suffix could be confusing. Must suffixes like `-beta` are *before* the actual release without suffix. As an example: `npm-check -u` wants to upgrade `0.19.0-rev4` to `0.19.0`.

![image](https://user-images.githubusercontent.com/13085980/66210564-70a9ea00-e6ba-11e9-84d2-26bbce348e0e.png)

## Possible improvement

So maybe it is an optionto use `${elm-version}.${rev}` (e.g. `0.19.0.x`)  for future releases instead?

Comparing with [hackage](https://docs.haskellstack.org/en/stable/maintainers/releases/#version-scheme) this wouldn't be the same way they propose the use it, but it could help clarify the order of versions - for humans and machines.

## Side note

Similar issues are occuring for `elm`, where a `2.0.0` is released but deprecated.
https://github.com/dylang/npm-check/issues/314

**Comment by harrysarson** [comment]
It would fit with what [v8 does](https://v8.dev/docs/version-numbers)

**Comment by andys8** [comment]
Docs say the example `42.6.7.9.3-alpha` is parsed as `42.6.7`. So it looks like it could be not possible to have four figure version based on the documentation.

https://github.com/npm/node-semver/blob/master/README.md#usage

**Comment by lydell** [comment]
Wait what – 0.19.1 isn’t the latest version? Damn, I’m missing out on the latest and greatest in a couple of projects…

Also – it looks like you forgot to set the `latest` tag on the last release. When I do `npm install elm-test` in a new project I get 0.19.1-revision2, but 0.19.1-revision3 seems to have been released.

**Comment by harrysarson** [comment]
Maybe we should publish a new package `elm-test-0.19.1` (if that is allowed). That package can follow normal semver. Then we publish `elm-test-0.19.2` or `elm-test-0.20.0` etc when the elm compiler updates?

**Comment by lydell** [comment]
I think this will be solved by following the suggestion in #447:

> I think the conclusion is that we should keep the current versioning system, with one change: We should _always_ have a `-revisionX` suffix. Currently it’s unclear if 0.19.1 or 0.19.1-revision4 is the latest. When Elm 0.19.2 or Elm 0.20.0 is released we should release 0.19.2-revision1 or 0.20.0-revision1 to avoid that confusion in the future.

**Comment by harrysarson** [comment]
Thanks @lydell!
