### ISSUE TITLE
Targeting specific tests not working consistently

### ISSUE THREAD

**Issue by zwilias** [rtfeldman/node-test-runner#391]
On the current release (`0.19.1`), pointing to specific paths to look for tests does not work consistently. This seems to be a caching issue.

There is some info on how to reproduce this over here: https://github.com/zwilias/elm-demystify-decoders/issues/9

Deleting `elm-stuff/generated-code` between runs fixes the issue. Deleting `elm-stuff/generated-code/[...]/elm.json` _partially_ fixes the issue: new tests are added to the set, but old tests run twice!

@rtfeldman this might interest you 😄

**Comment by rtfeldman** [comment]
Argh, thanks for reporting!
