### ISSUE TITLE
Very slow test runs caused by elmi-to-json

### ISSUE THREAD

**Issue by edmellum** [rtfeldman/node-test-runner#393]
Our test runs are taking 30-60 seconds on machines where compiling our project takes 3 seconds(60k lines of Elm, 1000 tests). I’ve looked around a bit and to me it looks like elmi-to-json is the culprit, it generates over 150mb(350kb-ish for hello world) of JSON which takes well over ten seconds and eats up my processor. From reading the node-test-runner source it looks like this is only used to match the module name? Is this a design flaw or am I looking at this wrong? If this is an important feature to the project, might it be possible to make it optional to use elmi-to-json for projects that favor a faster test run?

I’ve also tried using the newest elmi-to-json on my project directly and it’s taking 17 seconds to generate the JSON. The entire test suite is run in under 2 seconds.

**Comment by rtfeldman** [comment]
https://github.com/rtfeldman/node-test-runner/pull/396 should address this once we release it. (There are some other changes we want to get in first.)

@edmellum if you get a chance, can you try building from source on `master` and seeing if that improves things?

Here's how to do that:

1. Clone this repo somewhere
2. Run `npm install` in the cloned repo
3. `cd` into your Elm project's root directory
3. Run `(path-to-cloned-node-test-runner-directory-goes-here)/bin/elm-test`

**Comment by edmellum** [comment]
This is a big improvement! 😄 We are now down to 7 seconds on a MacOS machine and 10.5 seconds on a Windows machine. Still, this is 5.5 and 8 seconds overhead on Mac and Windows and makes TDD very hard to do as the time is the same with watch mode.

**Comment by harrysarson** [comment]
Fixed!
