### ISSUE TITLE
elm-test@latest-0.19.0 might use elm 0.19.1

### ISSUE THREAD

**Issue by andys8** [rtfeldman/node-test-runner#395]
When executing `npx elm-test@latest-0.19.0` it returned.

```
-- ELM VERSION MISMATCH ----------------------------------------------- elm.json

Your elm.json says this application needs a different version of Elm.

It requires 0.19.0, but you are using 0.19.1 right now.

Compilation failed while attempting to build /tmp/elmjson/tests/Test.elm
```

So it used `elm` on the path (which is `0.19.1`) and these version won't work together. Is this expected?

Adding the compiler path will work.`npx elm-test@latest-0.19.0 --compiler /home/user/bin/elm-0.19.0` is working.

**Comment by rtfeldman** [comment]
Yeah that's working as designed (although maybe not as expected!) - if you don't pass `--compiler` it defaults to whatever's on the `PATH`.

**Comment by andys8** [comment]
Thanks for clarification, Richard.
