### ISSUE TITLE
upgrade to 0.17

### ISSUE THREAD

**Issue by proProbe** [rtfeldman/node-test-runner#40]
Hello feldman!

Must first say that I love your work.
Im wondering if there will be a 0.17 port of this related to the community-elm/elm-test?

**Comment by pbiggar** [comment]
this is the output I get when I try to run elm-test under Elm 0.17 is:

```
 $ elm-test ConsoleRunner.elm
Success! Compiled 1 module.
Successfully generated /var/folders/_0/c4p0nhh561v1375f10b5mltw0000gn/T/elm_test_11654-23433-hh4ln3.zbny11nhfr.js
Successfully compiled ConsoleRunner.elm
Running tests...
  26 suites run, containing 55 tests
  All tests passed


: ""

[stdin]:10843
    if (typeof Elm === "undefined") { throw "elm-io config error: Elm is not defined. Make sure you call elm-io with a real Elm output file"}
                                      ^
elm-io config error: Elm is not defined. Make sure you call elm-io with a real Elm output file
```

It looks to me like elm wraps the test in a function, which then isn't available to the suffix that elm-test adds from elm-io-ports. I think they need to be added within the function.

**Comment by rtfeldman** [comment]
Yep! It's underway, but probably won't be done for another couple of weeks. 😄

**Comment by rtfeldman** [comment]
It's done! 🎉
