### ISSUE TITLE
Test runner fails on Windows with >100 test files

### ISSUE THREAD

**Issue by edmellum** [rtfeldman/node-test-runner#405]
With 125 test files in a project that is in a shallow directory on Windows, test runs fail with the following message: "The command line is too long. Compilation failed while attempting to build ..." followed by paths to the files. Windows seems to have a command line length limitation that I assume is being hit when spawning the elm compiler process.

**Comment by mpizenberg** [comment]
Hi @edmellum is it still the case with the latest version of elm-test 0.19.1-revision6?

**Comment by theothornhill** [comment]
It looks like it is fixed with `revision6` for us now. Great - thanks :)

**Comment by harrysarson** [comment]
Good news! Thanks for the report and following up
