### ISSUE TITLE
Issues with Debug.log and test reports

### ISSUE THREAD

**Issue by mpizenberg** [rtfeldman/node-test-runner#409]
I am currently helping the Elm track on exercism.io to get online capabilities. People could edit exercises online, submit and get the results of the tests, without needing to use exercism CLI. A key feature is the ability to report tests results in the interface. For this we use the [`--report junit`](https://github.com/exercism/elm-test-runner/blob/master/bin/run.sh#L36) feature.

When students have failing tests, they tend to use `Debug.log` to try figuring out what is wrong (as in #327). However, that makes the generated report invalid (as explained in #365). Fortunately, it seems that with junit report, the xml is at the end of the stream (btw, could you confirm that is the case?), so we can retrieve a valid report by truncating the start.

The second issue is regarding readability. We only present one failing test to the student, but we don't know which debug logging is relevant for that test. Since all functions with logging called by the tests will print to stdout, it makes a lot of noise. For now we thus prefer to completely ignore and not report logging.

If there was a way to capture `Debug.log` with associated tests (as in #400), that would be awesome. In the junit format, there are `system-out` and `system-err` tags that could be used for those.

**Comment by harrysarson** [comment]
Let's track in #365 (I would love a solution for this but do not have the personal motivation to fix it myself).
