### ISSUE TITLE
Terminal behavior breaks after first run

### ISSUE THREAD

**Issue by drewolson** [rtfeldman/node-test-runner#414]
I initially opened an issue on `elm-test` but it seems the issue is with this library. A description is here: https://github.com/elm-explorations/test/issues/132

In a nutshell, after running `elm-test`, commands like `ctrl+p` and up arrow are broken in the terminal.

**Comment by drewolson** [comment]
FYI, here's an example of a terminal session that breaks after running `elm-test`. I'm seeing this behavior on both macos and linux.

![terminal](https://user-images.githubusercontent.com/3536/78461303-65e20900-768d-11ea-9408-9b85dc7ae145.gif)

**Comment by harrysarson** [comment]
Hey @drewolson, would it be possible to confirm if this still happens with version `0.19.1-revision6`?

**Comment by drewolson** [comment]
This is indeed solved with `0.19.1-revision6`. Thanks!

**Comment by harrysarson** [comment]
Brilliant! @lydell another one you managed to fix even without realising
