### ISSUE TITLE
Vulnerability in used minimist version?

### ISSUE THREAD

**Issue by szabba** [rtfeldman/node-test-runner#415]
I have `elm-test` installed as a dev dependency with yarn.
Github has reported that the version of [`minimist`](https://www.npmjs.com/package/minimist) used by `elm-test` (1.2.0) has a vulnerability.
According to the report this is fixed since version 1.2.3.

![image](https://user-images.githubusercontent.com/820119/78832561-c5247e00-79eb-11ea-9466-989b1eefa323.png)

**Comment by harrysarson** [comment]
I will merge a pull request to bump any direct deps of the project!

**Comment by szabba** [comment]
Actually it seems like github has already made PR #413 for this. :)

**Comment by harrysarson** [comment]
See https://github.com/rtfeldman/node-test-runner/pull/413#issuecomment-611631513 alas.

**Comment by harrysarson** [comment]
#417 updates our direct dependency on minimist which fixes part the problem. Certainly it fixes any possible vulnerability in the test runner. (Saying that, if your threat model allows users to pass arbitrary flags to the executable then I would not trust this project further than I could throw it.)

#417 won't make `npm audit` happy though as we still pull the bad minimist version in via elm-format and elmi-to-json. If you want the warning to go away you will have to bug those libaries to upgrade and publish a new release and then get back to me to merge the bumps.

Saying all that I do not have npm publish rights so all of this is hypothetical.

**Comment by harrysarson** [comment]
I have released a new version of elm-test on npm with our dependancies unpinned. Hopefully, patches for the vulnerabilities `npm audit` found will filter through. Closing, but please re-open if there are actionable things we can do
