### ISSUE TITLE
Consider (not) using dependabot

### ISSUE THREAD

**Issue by harrysarson** [rtfeldman/node-test-runner#420]
I tried this before: https://github.com/rtfeldman/node-test-runner/issues/345 but I thought I might have a go again.

Dependabot is a service that automatically submits pull requests to keep dependancies in date. I have used I a lot (lately I have started using it more and more and greenkeeper less and less. They do the same thing but I find dependabot works slightly better). The issue blocking use of a service like this last time was that @rtfeldman did not want to give a third party app write access to this repository. I very fair point, however, I hope I have come up with a counter argument to win you back round.

1. Dependabot is owned by GitHub (https://dependabot.com/blog/hello-github/).
2. We trust github with write access to our repository (via the big green merge pull request button).
3. We therefore trust dependabot with write access to our repository.

:tada:

**Comment by harrysarson** [comment]
1. I am not hearing any arguments against this.
2. Dependabot has started making PR's already #434 (without anyone granting it permissions)

**Comment by lydell** [comment]
This was done in: https://github.com/rtfeldman/node-test-runner/pull/516

However:

- We don’t really merge their PRs, resulting in GitHub PR and notification spam.
- When we do merge them, it results in `git log` spam.

I wouldn’t mind removing it. We could still have the GitHub built-in security stuff enabled. Other than that, it feels like we can update deps manually whenever we’re doing the next piece of work on this repo, or near a release.
