### ISSUE TITLE
Why are npm dependencies pinned?

### ISSUE THREAD

**Issue by lydell** [rtfeldman/node-test-runner#424]
Almost all npm dependencies of this package are pinned:

https://github.com/rtfeldman/node-test-runner/blob/b86ed4f87ee6a5908392afa5afdf4bc5443c5f38/package.json#L35-L51

Why? Isn’t it a good thing to allow a range, so people can get bug fixes and “security” fixes (which `npm audit` nags about) without having to update elm-test?

**Comment by harrysarson** [comment]
Thanks!
