### ISSUE TITLE
Port CI tests to mocha

### ISSUE THREAD

**Issue by harrysarson** [rtfeldman/node-test-runner#441]
We currently have some tests in https://github.com/rtfeldman/node-test-runner/blob/master/tests/ci.js that were originally a bash script and were ported to javascript some time ago. However, these tests do not use the mocha framework (unlike the other tests in <https://github.com/rtfeldman/node-test-runner/blob/master/tests>). 

If someone could take each test in the file (they are roughly split up by code like `
shell.echo('### Testing elm-test on example-application/');`) and put each test into the mocha `test("name", () => {})` format that would be great :) You may want to look at the tests in <https://github.com/rtfeldman/node-test-runner/blob/master/tests/flag.js> for inspiration.

There is some code in <https://github.com/rtfeldman/node-test-runner/blob/master/tests/ci.js> that uses `npm link` to make the global `elm-test` command run the code in your local repository. That can be left as is and mocha will run it before any tests. 

Drop a comment below if you are interested or have any questions!

**Comment by frankschmitt** [comment]
I'd like to give this one a shot. Just to clarify: you want the existing ci.js replaced with the new version? And: how can I verify the npm link stuff still works?
(my Javascript / npm experience is quite limited, but I love Elm and I'd like to contribute)

**Comment by harrysarson** [comment]
> you want the existing ci.js replaced with the new version? 

Exactly!

> how can I verify the npm link stuff still works?

The npm link stuff replaces the global `elm-test` exe with elm test from your local repository. (As if you published a new version of elm-test with your changes and then ran `npm install -g elm-test). The way to check it works is to modify the elm-test source code so that it crashes and make sure tests start failing!

**Comment by harrysarson** [comment]
Removing help wanted to give @frankschmitt time to have a go!

**Comment by lydell** [comment]
There are some nice improvements in ci.js here: https://github.com/rtfeldman/node-test-runner/pull/442/files#diff-669efeda79bb547b3537ab544fd28f75

What I did was to log more information when a test fails so it’s easier to understand what’s wrong.

It would be nice if the new mocha version can give helpful information on failures as well!

**Comment by frankschmitt** [comment]
@lydell So would it make sense to implement the changes based on the version from your PR? Or rather on the vanilla version?

**Comment by harrysarson** [comment]
@frankschmitt I would recommend basing your pull request on master but cherry picking this commit https://github.com/rtfeldman/node-test-runner/pull/442/commits/3141bccfd4eff12a574e22d85e5dcbc2f2928630. That should give @lydell credit in git but means we can land the improvements to the tests without having to wait for #442 to land. 

@lydell would this be okay with you?

**Comment by lydell** [comment]
Sure! I don’t care much about the credit, just that it’s easy to work with in the end.

**Comment by frankschmitt** [comment]
This is probably a very stupid question, but how do I cherry-pick this commit? According to the Github UI, it looks kinda special:

  "This commit does not belong to any branch on this repository. 

I naively tried :
  git cherry-pick 3141bccfd4eff12a574e22d85e5dcbc2f2928630  

in my fork of the repo which results in          
  fatal: bad object 3141bccfd4eff12a574e22d85e5dcbc2f2928630

I then tried 

   git remote add upstream https://github.com/rtfeldman/node-test-runner.git
   git fetch upstream
   git cherry-pick 3141bccfd4eff12a574e22d85e5dcbc2f2928630  

which gave me the same result. As a last resort, I tried

  git clone https://github.com/rtfeldman/node-test-runner.git node-test-runner-upstream
  cd node-test-runner-upstream 
  git cherry-pick 3141bccfd4eff12a574e22d85e5dcbc2f2928630

which again gave me the same error. I'm running out of ideas now - I could download the changed file and manually overwrite the existing one, but surely there must be an easier way, and I'm just to blind to see it?

**Comment by lydell** [comment]
I think something like this should do the trick:

```
git remote add lydell git@github.com:lydell/node-test-runner.git
git fetch lydell js
git cherry-pick 3141bcc
```

**Comment by lydell** [comment]
But it might be easier to just copy file in the end (I’m not 100% I did all the improvements in one commit).

**Comment by harrysarson** [comment]
This one does the trick for me:

```
git remote add lydell git@github.com:lydell/node-test-runner.git
git fetch lydell js
git cherry-pick 3141bcc
```

**Comment by harrysarson** [comment]
@frankschmitt. We just landed all the changes from #442  that effect `./tests/ci.js` in a separate PR. If you update your branch with the latest master branch you should now be good to go!

Sorry, for the overlapping changes here!

**Comment by frankschmitt** [comment]
@harrysarson No worries. I've updated my fork and resolved the conflicts in my branch. 
Out of curiosity: how could I have detected that I needed to add @lydell 's Repo for the cherry-pick ? I just re-checked it, but the commit is displayed in the main repo (rtfeldman/node-test-runner.git). Is this a glitch in the Github UI?

**Comment by harrysarson** [comment]
The commit is somewhere within the main repo. I think github automatically makes a branch somewhere. To cherry-pick the commit you need to fetch the branch but I do not know the git commands for that. Or something like that?

**Comment by frankschmitt** [comment]
It‘s not really important, I was just curious (meanwhile, I‘ve cherry-picked it and pulled your updates).
