### ISSUE TITLE
Error in 'should work with different elm on PATH' if no other elm version is installed

### ISSUE THREAD

**Issue by frankschmitt** [rtfeldman/node-test-runner#449]
When running the tests with 'npm link; npm run test-only', I get a failure for one of the --compiler tests in flags.js

> 
> --compiler
>       ✓ Should fail if the given compiler can't be executed (604ms)
>       1) Should work with different elm on PATH
>       ✓ Should work with local different elm (2104ms)
>     --watch
>       ✓ Should re-run tests if a test file is touched (3900ms)
> ...
>  1) flags
>       --compiler
>        Should work with different elm on PATH:
>     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it 
> resolves. (/home/frank/src/3rd_party/node-test-runner-upstream/tests/flags.js)

I assume this is because I have only one version of Elm installed; System info:

Elm version: 0.19.1
Ubuntu 20.04.1 LTS

Is this test supposed to fail if only one Elm version is installed? If yes, I'd suggest we display a helpful error message, something along the lines of "This is supposed to fail if you don't have additional Elm versions installed on your system"

**Comment by harrysarson** [comment]
Try increasing the timeout. Maybe this test is just a bit slow 🐌

**Comment by frankschmitt** [comment]
That seems to fix it (I also started getting timeouts in test-quality.js for example-application). I'll prep a short PR if that's ok with you.
