### ISSUE TITLE
Access denied on -g installation

### ISSUE THREAD

**Issue by SimonShapiro** [rtfeldman/node-test-runner#477]
I am getting `access denied` with the following details on the `npm install -g elm-test`

```
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/usr/local/lib/node_modules/elm-test/node_modules/elmi-to-json/unpacked_bin'
```
As a work around I have installed it locally and start it with `nom run elm-test`.  But I wonder why this is happening.  As an aside, I am using a MacBook Air.

**Comment by SimonShapiro** [comment]
On testing while `npm run elm-test --version` works, `nom run elm-test install` does not.  So the workaround is not correct.

**Comment by lydell** [comment]
The upcoming version of elm-test does not depend on elmi-to-json anymore so chances are this is fixed by then. Maybe you can try that, actually: `npm install -g rtfeldman/node-test-runner`

**Comment by SimonShapiro** [comment]
`npm install -g rtfeldman/node-test-runner` still had the problem but in a different place.  `node_modules/.bin/elm-test` after a local install did work.

**Comment by lydell** [comment]
Thanks for trying that out! In what state is this issue, then?

**Comment by SimonShapiro** [comment]
Well, it's still an issue as it is not install as `-g`.  But I have a work around.  I guess if there is a pending new version that fixes it, we can close the issue.

**Comment by lydell** [comment]
Alright! Feel free to close it then!

**Comment by harrysarson** [comment]
Is this your issue: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally ?

**Comment by SimonShapiro** [comment]
That looks like it is. I will take a look at it tomorrow.

Many thanks.

**Comment by harrysarson** [comment]
A pleasure! Do reopen this issue if there are any more problems :)
