### ISSUE TITLE
Avoid duplicating the deps of the parent project

### ISSUE THREAD

**Issue by lpil** [rtfeldman/node-test-runner#48]
Currently it seems that in order to run tests we need to have all the parent projects deps also listed in the test project's `elm-package` file. This is going to be hard to maintain. It would be good if we could have a mechanism to keep these in sync.

How about the first thing that the `elm-test` executable is to read the parent project's `elm-package` and write any missing deps into the test projects deps? It could also sync versions.

**Comment by rtfeldman** [comment]
This is totally true, and I agree it's totally annoying. 😄 

There are plans to address this in `elm-package` itself, most likely in 0.19. I think that'll be the most sensible long-term solution, and I think in the meantime I don't think it'll be worth the effort to do a stopgap solution.

We've been syncing this manually for over a year at work, and although it's annoying, it's not so bad I think it's worth a temporary fix. 😃 

Thanks for the suggestion though!

**Comment by lpil** [comment]
Thank you :)
