### ISSUE TITLE
Automatically run elm package install if deps are missing

### ISSUE THREAD

**Issue by lpil** [rtfeldman/node-test-runner#49]
If deps are missing currently the user gets an error message and has to work out how to resolve the issue themselves. It seems we could do this for them and avoid this workflow bump entirely.

**Comment by rtfeldman** [comment]
I just made it always use `--yes`, so now it should just download them. 😄

**Comment by lpil** [comment]
Thank you

**Comment by gampleman** [comment]
Does that mean you can delete 

```
  - pushd tests && elm-package install -y && popd
```

from the .travis.yml example in the readme?
