### ISSUE TITLE
Using stdout or stderr for the error message when no test was found?

### ISSUE THREAD

**Issue by mpizenberg** [rtfeldman/node-test-runner#495]
Currently, the console report writes to stderr, the json report writes an equivalent escaped string to stdout, and the junit report crashes with the following message, repeated 8 times (I guess since I have 8 threads):
```
Error: connect ECONNREFUSED /tmp/elm_test-266283.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/tmp/elm_test-266283.sock'
}
```
Except for the junit crash which is probably a bug, it could make sense to have different behavior. Console output reports all failure logs in stderr, and json output uses an escaped string written to stdout probably because that's what tools are reading. I just wanted to point at the differences and maybe get some insight on those decisions since I have to choose which output to use for elm-test-rs.

**Comment by lydell** [comment]
I looked into this and it’s a regression since 0.19.1-revision5. Before that, a human readable message was written to stderr regardless of report format. I’ll make a PR to restore that.

**Comment by mpizenberg** [comment]
Alright I'll add an error message to stderr in all cases too!
