### ISSUE TITLE
Module not founded after move test file from `/tests`  to `/src`  folder

### ISSUE THREAD

**Issue by ravecat** [rtfeldman/node-test-runner#502]
After reading [docs](https://github.com/rtfeldman/node-test-runner#where-to-put-tests) I tried to move test file from `/tests`  to `/src`  folder. And got IDE error `Module not found`

But test running successfully for both case `elm-test src/**/*Test.elm` and `elm-test`. 

| OK | Fail |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/24782863/114116954-57f14480-98ee-11eb-9850-4db62165988a.png) |![image](https://user-images.githubusercontent.com/24782863/114117180-c6ce9d80-98ee-11eb-9af9-9534e45fc67f.png)|

IDE - VSCode (elm-tooling available)
elm.json - [here](https://pastebin.com/BmDyPHFG)

**Comment by lydell** [comment]
I might be wrong, but I think the Elm Language Server does not support tests outside the `tests/` folder. @Razzeee do you know?

**Comment by Razzeee** [comment]
Not supported. There's an issue, but nobody is working on it.

**Comment by harrysarson** [comment]
If I understand correctly, there is nothing actionable from the point of view of the test runner here. The issue (feature request) here is with the ide integration and is best tracked over there. 

Does that fit with your understanding @ravecat ?

**Comment by ravecat** [comment]
@harrysarson you're right

let me explain why I decided create issue. I found info about transfer test file to another folder [here](https://github.com/rtfeldman/node-test-runner#where-to-put-tests)

> There are 3 places you could put your tests:
> 2. In any source directory ("source-directories" in elm.json for applications, src/ for packages) 
> You might also need to configure your editor 

and thought you can explain how to set up it

**Comment by harrysarson** [comment]
Makes sense! Closing this one because there is nothing we can do from the elm-test side of things.
