### ISSUE TITLE
Intermittent missing dependency errors

### ISSUE THREAD

**Issue by sentience** [rtfeldman/node-test-runner#503]
Coming back to a codebase after some time, I'm experiencing intermittent failures running elm-test. I've upgraded to the latest version (0.19.1-revision6) but the issues persist. In particular, when I run `elm-test --watch`, my test runs sometimes run normally, but a significant amount of the time they fail with these errors:

```
-- MODULE NOT FOUND - /Users/kyank/code/murmur/node_modules/elm-test/elm/src/Console/Text.elm

You are trying to import a `Test.Runner.Node.Vendor.Console` module:

17| import Test.Runner.Node.Vendor.Console as Console
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
I checked the "dependencies" and "source-directories" listed in your elm.json,
but I cannot find it! Maybe it is a typo for one of these names?

    Test.Runner.Node
    Test.Runner.Failure
    Test.Generated.Main
    Test.Reporter.Reporter

Hint: If it is not a typo, check the "dependencies" and "source-directories" of
your elm.json to make sure all the packages you need are listed there!

                                                             Console.Text  ↑    
====o======================================================================o====
    ↓  Test.Generated.Main


-- MODULE NOT FOUND -------------------------------- src/Test/Generated/Main.elm

You are trying to import a `Test.Reporter.Reporter` module:

6| import Test.Reporter.Reporter exposing (Report(..))
          ^^^^^^^^^^^^^^^^^^^^^^
I checked the "dependencies" and "source-directories" listed in your elm.json,
but I cannot find it! Maybe it is a typo for one of these names?

    Test.Html.Selector
    Test.Runner.Failure
    Test.Generated.Main
    Test.Html.Event

Hint: If it is not a typo, check the "dependencies" and "source-directories" of
your elm.json to make sure all the packages you need are listed there!

-- MODULE NOT FOUND -------------------------------- src/Test/Generated/Main.elm

You are trying to import a `Test.Runner.Node` module:

8| import Test.Runner.Node
          ^^^^^^^^^^^^^^^^
I checked the "dependencies" and "source-directories" listed in your elm.json,
but I cannot find it! Maybe it is a typo for one of these names?

    Test.Runner
    Test.Runner.Failure
    Json.Encode
    Test.Html.Event

Hint: If it is not a typo, check the "dependencies" and "source-directories" of
your elm.json to make sure all the packages you need are listed there!


`elm make` failed with exit code 1.
Watching for changes...
```

I'm not sure where to start with troubleshooting this, as the issue seems to be with the codegen that goes on inside node-test-runnner. Anyone able to share any pointers?

**Comment by lydell** [comment]
Next time it happens you can try:

```
cd elm-stuff/generated-code/elm-community/elm-test/0.19.1-revision6
elm make src/Test/Generated/Main.elm --output /dev/null
```

And see if that triggers the same Elm compilation error. If so, it should be easier to troubleshoot! That folder contains an application elm.json and one Elm source file. "source-directories" contains a bunch of `"../../../../foo"` entries that includes stuff from your project as well as from `node_modules/elm-test/elm/src`. So it should be possible to check stuff like “_does_ that file/directory exist?”.

**Comment by sentience** [comment]
@lydell Confirmed, I can reproduce this following your instructions!

The dependencies missing in the compiler output (above) are `Test.Runner.*` and `Test.Reporter.*`. Where are these modules normally located? In the generated app that is failing to compile for me, the `../../../../../../../../../node_modules/elm-test/elm/src` directory only contains `Console` as a subdirectory, not `Test`.

**Comment by sentience** [comment]
Interestingly, when I run `elm-test` using the copy I installed globally with `yarn add global`, it works every time. The intermittent errors above only occur when I run my project-local install of `elm-test`, with this (shell-scripted) command:

```
../../../../../../../../../node_modules/.bin/elm-test --compiler ../../../../../../../../../node_modules/.bin/elm
```

**Comment by lydell** [comment]
That’s odd: The directory is supposed to contain both `Console` and `Test`: https://unpkg.com/browse/elm-test@0.19.1-revision6/elm/src/

**Comment by lydell** [comment]
You’re not using [yarn autoclean](https://classic.yarnpkg.com/en/docs/cli/autoclean/) by any chance, and that removes stuff named `Test` etc?

**Comment by sentience** [comment]
Some context that might be relevant:

My project (for which package.json installs elm and elm-test locally) contains ~20 separate elm.json apps in deeply-nested directories. I have a shell script that finds every one of those apps that contains tests, and runs elm-test for it, one at a time. So I'm running that one locally-installed copy of elm-test against a series of different Elm apps in sequence.

I'm not sure how that could explain the behaviour I'm seeing, but I highlight it because I suspect it's the thing that's "weird" about my use-case.

**Comment by sentience** [comment]
> You’re not using [yarn autoclean](https://classic.yarnpkg.com/en/docs/cli/autoclean/) by any chance, and that removes stuff named `Test` etc?

Nailed it! We do indeed have a .yarnclean file that is deleting `tests`, and my file system is case-insensitive!

Thank you. :)

**Comment by lydell** [comment]
Should we

- consider this solved and close the issue?
- rename the internal Elm modules to avoid names commonly removed by `yarn autoclean`?

**Comment by sentience** [comment]
Yarn autoclean's docs come with a strong warning to customize your configuration to avoid this sort of thing, so it's our fault for missing it. I think we can close and hope anyone else facing this will find this issue via Google.
