### ISSUE TITLE
Crash when --output is set for `elm-test make`

### ISSUE THREAD

**Issue by juanedi** [rtfeldman/node-test-runner#508]
Hey! I've been running into some problems when trying to compile Elm tests within Emacs.

The Emacs plugin makes use of the `--output` flag for `elm make` so that users can later use the editor's compilation output ([code here](https://github.com/bsermons/flycheck-elm/blob/master/flycheck-elm.el#L173-L179)). When I try to compile test files (using `elm-test` instead of `elm`) I'm getting `error: unknown option '--output=/dev/null'`.

I first thought about raising this as an issue for flycheck-elm, but after reading https://github.com/rtfeldman/node-test-runner/issues/284 it seemed to me like the intention of `elm-test make` was to be compatible with `elm make` to facilitate editor integration.

I don't know if other editor plugins make use of `--output`, but it didn't seem too weird of a use case so I figured it might make sense to do something here instead of fixing at the plugin level. Would that make sense?

**Comment by harrysarson** [comment]
I am 99% sure that elm-test make never produces any output files. The make subcommand just checks that your tests compile.

Previous we ignored unknown flags but now we raise an error. You can safely delete `--output /dev/null`.

**Comment by juanedi** [comment]
Yeah, I guess I was wondering if `elm-test` should actually ignore that flag when running `make`, with the intention of preserving compatibility with `elm make`.

If we agree that setting `--output` is a reasonable thing for editor plugins to do, then it might make sense to do this instead of expecting every plugin to worry about whether which command is being run and conditionally skip the argument.

TBH that seems like more robust solution to me considering how:

  - AFAIK most editor plugins don't give end users a lot of flexibility for customizing the command and its arguments
  - it might not be trivial for the plugin to detect which program is actually being called
  - `elm-test make` seemed to be meant specifically for editor integration

Thoughts? Thanks for the quick reply!

**Comment by lydell** [comment]
> I am 99% sure that elm-test make never produces any output files.

Just for the record: Yes. `elm-test make` uses `Compile.compileSources` (https://github.com/rtfeldman/node-test-runner/blob/c493674c278e7a2d6f66742b68296af4eb9d8dbd/lib/elm-test.js#L196) and `Compile.compileSources` has `output: '/dev/null'` hard coded (https://github.com/rtfeldman/node-test-runner/blob/c493674c278e7a2d6f66742b68296af4eb9d8dbd/lib/Compile.js#L43). It might still other stuff to `./elm-stuff/generated-code/elm-community/elm-test/0.19.1-revision6/`, like `elm.json`.

---

Re ignoring `--output`, that makes me think of GNU make:

```
❯ make --help
Usage: make [options] [target] ...
Options:
  -b, -m                      Ignored for compatibility.
```

So it’s not unheard of to ignore some flags for compatibility.

In the case of elm-test it might make sense to do this if it helps all emacs users. It should be easy to do. We can even hide `--output` from the `--help` text.

**Comment by harrysarson** [comment]
I would be worried about letting users supply files other than /dev/null for output and silently ignoring it.

**Comment by lydell** [comment]
Yeah. Maybe _only_ `/dev/null` should be valid if `--output` is provided. So `--output /dev/null` is ok, but `--output something.js` is invalid.

**Comment by harrysarson** [comment]
@juanedi would elm-test ignoring `--output` if and only if the path is `/dev/null` work for your use case?

**Comment by juanedi** [comment]
Yes it would! I tried wrapping `elm-test` with a tiny script that ignores --output in this case and it works like a charm 👍 

Thanks for considering this! Would you like me to take a crack at it and make a PR?

**Comment by harrysarson** [comment]
Go for it! I would tentatively suggest putting a warning on stdout that the flag has no effect.
