### ISSUE TITLE
Unable to install npm package for 0.18.13-beta4

### ISSUE THREAD

**Issue by 97jaz** [rtfeldman/node-test-runner#509]
The binaries are (or, rather, were) hosted at bintray, which was shut down, according to [this discussion thread](https://discourse.elm-lang.org/t/psa-old-elm-binary-downloads-now-gone/7319). (The install process tries to download https://dl.bintray.com/elmlang/elm-test/0.18.13/linux-x64.tar.gz.)

Oddly, there doesn't appear to be a git tag for 0.18.13 in this repo.

**Comment by 97jaz** [comment]
Sure -- here's an excerpt from the install log that my colleague provided:
```
#11 15.35 error /usr/local/share/.config/yarn/global/node_modules/elm-test: Command failed.
#11 15.35 Exit code: 1
#11 15.35 Command: node install.js
#11 15.35 Arguments:
#11 15.35 Directory: /usr/local/share/.config/yarn/global/node_modules/elm-test
#11 15.35 Output:
#11 15.35 Downloading binaries from https://dl.bintray.com/elmlang/elm-test/0.18.13/linux-x64.tar.gz
#11 15.35 Error decompressing https://dl.bintray.com/elmlang/elm-test/0.18.13/linux-x64.tar.gz Error: incorrect header 
```

The "incorrect header" error is the result of trying to gunzip the file at `https://dl.bintray.com/elmlang/elm-test/0.18.13/linux-x64.tar.gz` -- which, if you visit that URL, you'll see is a 403 (Forbidden) error page.

**Comment by lydell** [comment]
Related: https://github.com/lydell/elm-old-binaries/issues/1

As far as I can tell, the binary in question is https://github.com/stoeffel/elm-interface-to-json. It might be possible to build it from source.

**Comment by 97jaz** [comment]
@lydell You're right. I was able to get the file from the Wayback Machine, and it does, in fact, contain `elm-interface-to-json`.

**Comment by lydell** [comment]
I’ve downloaded elm-interface-to-json binaries for all platforms from web.archive.org.

I’ve made a branch – [0.18](https://github.com/rtfeldman/node-test-runner/tree/0.18) – here which changes to download from https://github.com/rtfeldman/node-test-runner/releases/tag/0.18.13 (yes I went ahead and made a release so we can verify that it works).

The `0.18` branch is based on [0.18-security](https://github.com/rtfeldman/node-test-runner/tree/0.18-security), which seems to be the branch that 0.18.13-beta4 was released from. Relevant PRs:

- https://github.com/rtfeldman/node-test-runner/pull/304
- https://github.com/rtfeldman/node-test-runner/pull/307

The only difference between 0.18.13 and 0.18.13-beta4 seems to be dependency security updates.

The test suite passes locally.

@97jaz Can you try out 0.18.13? You can install it by running `npm install rtfeldman/node-test-runner#0.18.13`.

When that’s done, @harrysarson needs to (I don’t have access to the npm package):

- Check out the `0.18` branch locally.
- Run `npm publish --tag latest-0.18.0`
- Run `npm dist-tag add elm-test@0.18.13 elm0.18.0`

(I might have made mistakes in the npm commands above.)

**Comment by 97jaz** [comment]
@lydell I successfully built our Docker image, installing both elm 0.18 (downloading and copying the binaries) and elm-test 0.18 (via npm). Thanks!

(Oh, after writing this I realized that the tag you mentioned is `0.18.13`. I used `#0.18`, which will refer to the branch rather than the tag. I suppose I should change that, in case the branch is deleted. At any rate, it worked.)

**Comment by lydell** [comment]
elm-test 0.18.13 is now on npm as well!
