### ISSUE TITLE
Erroneously requires indirect dependencies specified for packages during watch

### ISSUE THREAD

**Issue by emilgoldsmith** [rtfeldman/node-test-runner#512]
Hi!

So I'm building a package that depends on `elm/html`, and as far as I understand and I can see other packages doing I'm not supposed to specify indirect dependencies.

However if I use `elm-test watch` it works fine at first (and also without watch), but then it seems to fail for example when I change an export but I also think similar things with changing anything surrounding imports with the following error:

```
-- MISSING DEPENDENCIES ----------------------------------------------- elm.json

Your elm.json is missing some "indirect" dependencies:

    "elm/virtual-dom": "1.0.2"

This usually means you are editing elm.json by hand. It is much more reliable to
use the elm install command instead.
```

I'm assuming it's when I trigger some kind of dependency check.

If there's a relatively simple solution I'd be happy to help implementing it

**Comment by lydell** [comment]
Hi! I tried to reproduce your issue: https://github.com/lydell/elm-test-pkg-test

I didn’t get any errors, though. Is there something I’m missing?

**Comment by emilgoldsmith** [comment]
Thanks for taking the time Simon! I’m about to go to bed now, but I’ll try
and iterate on yours to get a reproducible minimal example!

**Comment by emilgoldsmith** [comment]
Hmm now I can't reproduce it either.... Weird! 

If I encounter it again I'll try nailing down the cause a bit better, but I guess for now I'll close this issue, until we can understand it better
