### ISSUE TITLE
File watching

### ISSUE THREAD

**Issue by gampleman** [rtfeldman/node-test-runner#56]
It would be nice to support interactive testing where the runner watches loaded files for changes and reruns the tests when the files change. I think this would be particularly nice if it was optimized for speed so that once you hit save in  the editor you could see your tests finished by the time you switch to the console. To achieve this it would make sense to build these optimizations:

1. Work out the minimal subset of tests that need to run on a change. Given the following project:

   Main.elm imports A.elm and B.elm. B.elm imports C.elm. Each of these has a corresponding test file that only imports the file it tests. When I make a change to B.elm, I will only need to run tests from BTests.elm and MainTests.elm, since only these can have possibly changed.

   For this to work you would need to get the import tree from the compiler, which I don't know if it supported. When the dependency tree changes, it would make sense to re-run the entire suite.

2. Only run perhaps 10 fuzz tests rather than a hundred. Since you will run tests on every save, they should get decent coverage. You could perhaps run 100 on the first run.

Of course #51 would fit very well into this proposal as well.

**Comment by gampleman** [comment]
After doing some thinking about this proposal, the part that I'm struggling to see is how we could actually filter out the tests to run based on file/module names. I suppose there could be an alternative signature to `run` which would take a dict of module names and test values, but that seems a bit unpleasant to me.

**Comment by zkessin** [comment]
I have been using  chokidar to do that with the help of a few makefiles. that being said it would be nice to have in elm-test

````

{
    "scripts": {
        "watch": "chokidar '**/*.elm' --initial --debounce 750 --command ' make elm-test --silent'|| ntfy"
    }
}
````

**Comment by gampleman** [comment]
#74 only does the bare minimum, none of the actual interesting features proposed here. So I would like this to be reopened (I can edit the title to introduce some clarity in what is being requested).

/cc @rtfeldman .

**Comment by gampleman** [comment]
Another interesting feature that this work would support is for faster CI runs. You could work out only the set of files that have changed (i.e. by running `git diff`) and then run only the tests that need to be run - this could help alleviate problems especially from slow fuzz tests.

**Comment by rtfeldman** [comment]
@gampleman makes sense - would you mind opening a fresh issue that frames it in terms of changes to what's already released?

**Comment by gampleman** [comment]
Not sure what you mean by "persistence between runs". As far as I can understand, no persistence would be required as all that you would need would be stored in git.

So I'm thinking your travis config could look like this:

```
script:
  - git diff -u $TRAVIS_COMMIT_RANGE | elm test --with-unified-diff
```

I'll file the ticket for the watch mode improvements later on, but it seems to me that the two features are fairly similar.

**Comment by rtfeldman** [comment]
> As far as I can understand, no persistence would be required as all that you would need would be stored in git.

Not for that particular implementation, but other options seem worthwhile to explore. 😉

**Comment by gampleman** [comment]
Issues created for what was discussed above:

#110 and #111.
