### ISSUE TITLE
Running elm-test leaves fish shell in a weird state

### ISSUE THREAD

**Issue by jjant** [rtfeldman/node-test-runner#565]
After running `elm-test` in fish, the terminal is left in a weird state, with the next line not displaying properly sometimes.
It's hard to explain, but I'm guessing the program is writing some weird character somewhere.

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/15112080/153761333-cd073abe-abc8-4fd0-87b4-6b9708401f34.png">

Pressing Ctrl-C or Ctrl-L (clear screen) displays the control characters if you press them directly after running elm-test, these are not displayed in normal situations.

**Comment by lydell** [comment]
Hi! Can you test the latest version – revison7 (not 2) – and see if the same thing happens there?

**Comment by lydell** [comment]
> Any ideas what was causing it?

Apparently not: https://github.com/rtfeldman/node-test-runner/issues/414#issuecomment-776159638

But I would bet the more disciplined logging and `process.exit` usage when refactoring helped.
