### ISSUE TITLE
Run elm-make from node_modules if present

### ISSUE THREAD

**Issue by lpil** [rtfeldman/node-test-runner#57]
Hello!

Trying to use `elm-test` without the Elm platform installed globally results in an error like so:

```sh
$ ./node_modules/.bin/elm-test
Could not find Elm compiler "elm-make". Is it installed?
```

Could we run `elm-make` from `node_modules`  if it is present there? This would make it easier to work with multiple versions of Elm.

**Comment by rtfeldman** [comment]
Thanks for the post!

You can currently specify the `elm-make` to use via the `--compiler` flag, e.g. 

```
elm-test --compiler node_modules/.bin/elm-make Main.elm
```

A previous version used to auto-detect `node_modules/.bin/elm-make`, but there were cases where it was too surprising in practice. I'd have a stale version installed in `node_modules`, forget it was being used, install a new version globally, and then see surprising behavior in my tests. I think the potential for unpleasant surprises outweighs the utility of auto-detecting this.

So thanks again for the post, but I think it's better off being explicit. 😸

**Comment by lpil** [comment]
Ah, that's even better than my suggestion. I really should have read the `--help` output.

Would this be something good to note in the README?

**Comment by rtfeldman** [comment]
Sure! Would be happy to accept a PR to note that in README.
