### ISSUE TITLE
Mocha tests fail on modern Node versions

### ISSUE THREAD

**Issue by lishaduck** [rtfeldman/node-test-runner#633]
It looks like the repo could use some cleanup :)
The solution is the same as https://github.com/jfmengels/node-elm-review/issues/118#issuecomment-2174238016
The root cause is that JSON.parse returns better errors on modern node versions, so my node 20 has a different error than the repo's node 14(? 16?) (12 is the engine, so maybe that?)
What node do we want for tests? Should we patch the tests to ~equal? Patch the output? How do we want to go about fixing this?
With `elm-review`, we locked our node, but then we can't test for compatibility. I'd probably patch the tests to say it should equal one of different messages.

Found testing mpizenberg/elm-solve-deps-wasm#3.

**Comment by lishaduck** [comment]
P.S.: If you're comfortable, @lydell, I think elm-review's test suite is enough to merge https://github.com/mpizenberg/elm-solve-deps-wasm/pull/3 given that these don't seem to work, but if you'd prefer to test those changes first, I can work on this. I might either way :man_shrugging:

**Comment by lydell** [comment]
I already ran the tests myself, and had one test failing before and after installing your changes to elm-solve-deps-wasm due to the changed JSON.parse error messages. So that should be good to go.

To make the test pass again across Node.js versions, I’d just do the simplest thing that solves the problem in the test. Not sure what without looking closer to it.

**Comment by lishaduck** [comment]
> I already ran the tests myself, and had one test failing before and after installing your changes to elm-solve-deps-wasm due to the changed JSON.parse error messages. So that should be good to go.

Cool, thanks!

> To make the test pass again across Node.js versions, I’d just do the simplest thing that solves the problem in the test. Not sure what without looking closer to it.

I'll send in a PR to patch the comparison sometime.

**Comment by lishaduck** [comment]
Opened #634
