### ISSUE TITLE
elm test init should copy dependencies

### ISSUE THREAD

**Issue by mgold** [rtfeldman/node-test-runner#68]
The README for elm-test states that one needs to manually copy dependencies from the root elm-package.json to the test copy. Node is fully capable of reading files and parsing JSON so it would be a nice enhancement if running `elm test init` would handle this automatically. It could also do a similar check before running tests to keep the files up to date.

**Comment by eeue56** [comment]
Already done and implemented about 4 months ago here -> https://github.com/NoRedInk/elm-ops-tooling#elm_deps_sync

**Comment by halfzebra** [comment]
I have ported [elm-deps-sync](https://github.com/halfzebra/elm-deps-sync)

@rtfeldman would it make sense to integrate it into node-test-runner?

**Comment by rtfeldman** [comment]
It's already been done on a branch, and should be included in the next release!
