### ISSUE TITLE
Tests in different path than tests/Main.elm

### ISSUE THREAD

**Issue by sporto** [rtfeldman/node-test-runner#72]
In my project using previous version of elm-test I had 

`test/unit/`
`test/integration`

I was using `elm-make TestRunner.elm --output tests.js && node tests.js` to run the unit test.

I'm trying to upgrade to elm-test 2 and  `node-test-runner`. But it seems I need to put my test runner in `tests/Main.elm`.

I would like to put my Main file in `tests/unit/Main.elm`. Is there an option for this?

**Comment by jinjor** [comment]
Have you tried `elm-test tests/unit/Main.elm`?

I just found this option from source code, but there is '--help' option too. I think these should be documented in README.

**Comment by rtfeldman** [comment]
Update: the next release should make this nicer, because it will let you run `elm-test test/**/*.elm`
