### ISSUE TITLE
AST-like ouput for custom formatters

### ISSUE THREAD

**Issue by scottcorgan** [rtfeldman/node-test-runner#73]
The default format of the test output is great, but it would be awesome to have something like JSON or TAP output so that the community can create custom formatters (like mocha's dot or spec  outputs).

I wanted to open the conversation to see what some ideas could be.

**Comment by mgold** [comment]
You can run the tests yourself in within Elm using [Test.Runner](http://package.elm-lang.org/packages/elm-community/elm-test/latest/Test-Runner), and then output the format however you like. That said, Elm adheres to "only one way to do it" and "usecase-diven design" pretty strongly, so maybe lead with why you want a custom formatter and why the current one is unsuited to your needs?

**Comment by scottcorgan** [comment]
You know what, this isn't an issue and belongs on the mailing list instead.

I'll close and put there if it needs to be.
