### ISSUE TITLE
set default number of fuzz tests from command line

### ISSUE THREAD

**Issue by zkessin** [rtfeldman/node-test-runner#77]
It would be nice to be able to run a test run where each fuzz test did a much larger number of tests than the normal without having to change code. 

that is being able to do this

```
elm test --fuzz-itterations 10000
```

Or via an environment variable, but probably better on the command line

**Comment by rtfeldman** [comment]
What's a specific use case this would make nicer?

**Comment by zkessin** [comment]
Being able to run more tests to find the obscure bug that might only happen 1 time in 10,000 or so. I have seen bugs that showup via a property based test (in erlang) that just required an unusual combination of factors, so being able to have a build that could run everything a larger number of times would be helpful.

**Comment by rtfeldman** [comment]
Gotcha, makes sense. This is now implemented on a branch, and will be in the next release!
