### ISSUE TITLE
Document cli configuration flags

### ISSUE THREAD

**Issue by halfzebra** [rtfeldman/node-test-runner#86]
I think it would be super helpful, if [Configuration](https://github.com/rtfeldman/node-test-runner#configuration) section of REAMDE.md mentioned all available configuration options.

- [ ] yes
- [ ] warn
- [ ] version
- [ ] help
- [x] watch
- [x] compiler
- [x] seed
- [ ] report

**Comment by zwilias** [comment]
#155 covers this :)
