### ISSUE TITLE
elm-test doesn't find compiler when installed through NPM

### ISSUE THREAD

**Issue by Anahkiasen** [rtfeldman/node-test-runner#88]
I've installed both `elm` and `elm-test` locally through NPM, however `elm-test` doesn't seem to be able to locate `elm-make` by default:

```bash
$ elm-test
Could not find Elm compiler "elm-make". Is it installed?

$ which elm-make
node_modules/.bin/elm-make

$ elm-make
Success! Compiled 0 modules.

$ elm-test --compiler $(realpath node_modules/.bin/elm-make)
Success! Compiled 81 modules.
Successfully generated /var/folders/g1/xqkylmwn4_x8mkyh5rf2cgkh0000gn/T/elm_test_1161013-51250-ldbbs7.gg24mo0f6r.js

elm-test
--------

Running 3 tests. To reproduce these results, run: elm-test --seed 738405972
```

As you can see, manually specifying the path does works, but could it be possible to make elm-test also look into `node_modules/.bin` by default?

**Comment by rtfeldman** [comment]
Thanks for the suggestion!

It actually used to do this, but I don't like the idea of it silently switching to a different compiler from the one on your `PATH`. That's the sort of thing that saves a few seconds 9 times out of 10, and then eats an entire day the 10th time because that's the last thing you'd think to check for the behavior you're seeing. 😉 

For that reason I'd rather we stick to the current design.

**Comment by Anahkiasen** [comment]
I understand what you mean and I'm fine with it only looking in `PATH` but in this case `elm-make` is indeed in my PATH, it is the default binary outside of `elm-test` since I have the following in my profile file:

```bash
PATH=node_modules/.bin:$PATH
```

If I do `which elm-make` it does give me `node_modules/.bin/elm-make`, so shouldn't `elm-test` find it in this particular case?

**Comment by rtfeldman** [comment]
Got it - yeah I'd expect it to.

What happens if you run the example code in the README of https://github.com/rtfeldman/node-elm-compiler - does that work?

**Comment by Anahkiasen** [comment]
Hm this is what I get:

```
$ node compileHelloWorld.js
Error: You are using Elm 0.18.0, but this project is saying it needs a version
in this range: 0.17.0 <= v < 0.18.0

This means this package has not been upgraded for the newer version of Elm yet.
Check out the upgrade docs for guidance on how to get things working again:
<https://github.com/elm-lang/elm-platform/tree/master/upgrade-docs>


Finished with exit code 1
(node:44904) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Compilation failed
Error: You are using Elm 0.18.0, but this project is saying it needs a version
in this range: 0.17.0 <= v < 0.18.0

This means this package has not been upgraded for the newer version of Elm yet.
Check out the upgrade docs for guidance on how to get things working again:
<https://github.com/elm-lang/elm-platform/tree/master/upgrade-docs>



(node:44904) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:44904) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Compilation failed
Error: You are using Elm 0.18.0, but this project is saying it needs a version
in this range: 0.17.0 <= v < 0.18.0

This means this package has not been upgraded for the newer version of Elm yet.
Check out the upgrade docs for guidance on how to get things working again:
<https://github.com/elm-lang/elm-platform/tree/master/upgrade-docs>
```

**Comment by rtfeldman** [comment]
Gah, sorry! I just updated the example to Elm 0.18.

Can you git pull and try it again? :)

**Comment by Anahkiasen** [comment]
Without `npm i elm -g` I get the same thing as above (Could not find Elm compiler), with it seems to compile fine I think, I get a good dozen lines of JS so I think that's the expected output

**Comment by rtfeldman** [comment]
So here's the output I get if I try to `npm install elm` without `-g`:

```
$ which elm-make
/usr/local/bin/elm-make
$ npm remove -g elm
$ npm install elm
$ which elm-make
elm-make not found
$ npm install -g elm
/usr/local/bin/elm-make
```

It's definitely not ending up on my path. I'm curious why it'd be different for you... 🤔

**Comment by Anahkiasen** [comment]
Because I set it up like so, I put `PATH=node_modules/.bin:$PATH` in my `.zprofile` file. It's a common setup to avoid having to type `node_modules/.bin` all day, same for other package managers:

**~/.zprofile**
```bash
## Homebrew
PATH=/usr/local/bin:/usr/local/sbin:$PATH

## NPM
PATH=node_modules/.bin:$PATH

## Composer
PATH=vendor/bin:$HOME/.composer/vendor/bin:$PATH
```

**Comment by rtfeldman** [comment]
Ah, got it.

Okay, I wonder if somehow that `PATH` is not making it into Node properly.

When you run `node -p process.env.PATH` do you see `node_modules/.bin` in the output?

**Comment by Anahkiasen** [comment]
As far as I can see yes, so that's even weirder :D

```bash
$ node -p process.env.PATH
/Users/anahkiasen/bin:/usr/local/bin:vendor/bin:/Users/anahkiasen/.composer/vendor/bin:node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/anahkiasen/.composer/vendor/bin

$ node --version
v7.2.0
```

**Comment by rtfeldman** [comment]
Aha! This might be it: http://stackoverflow.com/questions/9679932/how-to-use-package-installed-locally-in-node-modules

When it runs `elm-make` it has to set the cwd to be the directory of the `elm-package.json` in question (in this case, presumably `tests/elm-package.json`), so unless `tests/node_modules/bin` exists, it won't be on the PATH as far as elm-test can tell.

What happens in you do `npm install elm` in the `tests/` directory?

**Comment by Anahkiasen** [comment]
That seems to work indeed so I'm guessing that is the issue. Abridged transcript:

```bash
$ elm-test
Could not find Elm compiler "elm-make". Is it installed?

$ cd tests && npm init -y && npm i elm

$ cd ..
$ elm-test
Running 3 tests. To reproduce these results, run: elm-test --seed 1831419900
```
