### ISSUE TITLE
Travis fails but AppVeyor & local tests pass

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/node-test-runner#96]
For example: https://travis-ci.org/rtfeldman/node-test-runner/jobs/179291777

**Comment by avh4** [comment]
The failure is

```
elm-io config error: Elm is not defined. Make sure you provide a file compiled by Elm!
ci.js: ERROR: PassingTests.elm: Expected tests to pass
```

**Comment by rtfeldman** [comment]
This is still true, but with a different error now: https://github.com/rtfeldman/node-test-runner/issues/125

**Comment by rtfeldman** [comment]
This is still true, but now it's just `node-test-runner`'s tests which fail, not other projects'. 😛

Example of current failure: https://travis-ci.org/rtfeldman/node-test-runner/jobs/232152966

**Comment by rtfeldman** [comment]
Fixed by @zwilias in https://github.com/rtfeldman/node-test-runner/pull/153
